// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.GitHub.OpenApiClient.Models;
using Soenneker.GitHub.OpenApiClient.User.Blocks;
using Soenneker.GitHub.OpenApiClient.User.Codespaces;
using Soenneker.GitHub.OpenApiClient.User.Docker;
using Soenneker.GitHub.OpenApiClient.User.Email;
using Soenneker.GitHub.OpenApiClient.User.Emails;
using Soenneker.GitHub.OpenApiClient.User.Followers;
using Soenneker.GitHub.OpenApiClient.User.Following;
using Soenneker.GitHub.OpenApiClient.User.Gpg_keys;
using Soenneker.GitHub.OpenApiClient.User.Installations;
using Soenneker.GitHub.OpenApiClient.User.InteractionLimits;
using Soenneker.GitHub.OpenApiClient.User.Issues;
using Soenneker.GitHub.OpenApiClient.User.Item;
using Soenneker.GitHub.OpenApiClient.User.Keys;
using Soenneker.GitHub.OpenApiClient.User.Marketplace_purchases;
using Soenneker.GitHub.OpenApiClient.User.Memberships;
using Soenneker.GitHub.OpenApiClient.User.Migrations;
using Soenneker.GitHub.OpenApiClient.User.Orgs;
using Soenneker.GitHub.OpenApiClient.User.Packages;
using Soenneker.GitHub.OpenApiClient.User.Public_emails;
using Soenneker.GitHub.OpenApiClient.User.Repos;
using Soenneker.GitHub.OpenApiClient.User.Repository_invitations;
using Soenneker.GitHub.OpenApiClient.User.Social_accounts;
using Soenneker.GitHub.OpenApiClient.User.Ssh_signing_keys;
using Soenneker.GitHub.OpenApiClient.User.Starred;
using Soenneker.GitHub.OpenApiClient.User.Subscriptions;
using Soenneker.GitHub.OpenApiClient.User.Teams;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.GitHub.OpenApiClient.User
{
    /// <summary>
    /// Builds and executes requests for operations under \user
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UserRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The blocks property</summary>
        public global::Soenneker.GitHub.OpenApiClient.User.Blocks.BlocksRequestBuilder Blocks
        {
            get => new global::Soenneker.GitHub.OpenApiClient.User.Blocks.BlocksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The codespaces property</summary>
        public global::Soenneker.GitHub.OpenApiClient.User.Codespaces.CodespacesRequestBuilder Codespaces
        {
            get => new global::Soenneker.GitHub.OpenApiClient.User.Codespaces.CodespacesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The docker property</summary>
        public global::Soenneker.GitHub.OpenApiClient.User.Docker.DockerRequestBuilder Docker
        {
            get => new global::Soenneker.GitHub.OpenApiClient.User.Docker.DockerRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The email property</summary>
        public global::Soenneker.GitHub.OpenApiClient.User.Email.EmailRequestBuilder Email
        {
            get => new global::Soenneker.GitHub.OpenApiClient.User.Email.EmailRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The emails property</summary>
        public global::Soenneker.GitHub.OpenApiClient.User.Emails.EmailsRequestBuilder Emails
        {
            get => new global::Soenneker.GitHub.OpenApiClient.User.Emails.EmailsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The followers property</summary>
        public global::Soenneker.GitHub.OpenApiClient.User.Followers.FollowersRequestBuilder Followers
        {
            get => new global::Soenneker.GitHub.OpenApiClient.User.Followers.FollowersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The following property</summary>
        public global::Soenneker.GitHub.OpenApiClient.User.Following.FollowingRequestBuilder Following
        {
            get => new global::Soenneker.GitHub.OpenApiClient.User.Following.FollowingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The gpg_keys property</summary>
        public global::Soenneker.GitHub.OpenApiClient.User.Gpg_keys.Gpg_keysRequestBuilder Gpg_keys
        {
            get => new global::Soenneker.GitHub.OpenApiClient.User.Gpg_keys.Gpg_keysRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The installations property</summary>
        public global::Soenneker.GitHub.OpenApiClient.User.Installations.InstallationsRequestBuilder Installations
        {
            get => new global::Soenneker.GitHub.OpenApiClient.User.Installations.InstallationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The interactionLimits property</summary>
        public global::Soenneker.GitHub.OpenApiClient.User.InteractionLimits.InteractionLimitsRequestBuilder InteractionLimits
        {
            get => new global::Soenneker.GitHub.OpenApiClient.User.InteractionLimits.InteractionLimitsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The issues property</summary>
        public global::Soenneker.GitHub.OpenApiClient.User.Issues.IssuesRequestBuilder Issues
        {
            get => new global::Soenneker.GitHub.OpenApiClient.User.Issues.IssuesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The keys property</summary>
        public global::Soenneker.GitHub.OpenApiClient.User.Keys.KeysRequestBuilder Keys
        {
            get => new global::Soenneker.GitHub.OpenApiClient.User.Keys.KeysRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The marketplace_purchases property</summary>
        public global::Soenneker.GitHub.OpenApiClient.User.Marketplace_purchases.Marketplace_purchasesRequestBuilder Marketplace_purchases
        {
            get => new global::Soenneker.GitHub.OpenApiClient.User.Marketplace_purchases.Marketplace_purchasesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The memberships property</summary>
        public global::Soenneker.GitHub.OpenApiClient.User.Memberships.MembershipsRequestBuilder Memberships
        {
            get => new global::Soenneker.GitHub.OpenApiClient.User.Memberships.MembershipsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The migrations property</summary>
        public global::Soenneker.GitHub.OpenApiClient.User.Migrations.MigrationsRequestBuilder Migrations
        {
            get => new global::Soenneker.GitHub.OpenApiClient.User.Migrations.MigrationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The orgs property</summary>
        public global::Soenneker.GitHub.OpenApiClient.User.Orgs.OrgsRequestBuilder Orgs
        {
            get => new global::Soenneker.GitHub.OpenApiClient.User.Orgs.OrgsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The packages property</summary>
        public global::Soenneker.GitHub.OpenApiClient.User.Packages.PackagesRequestBuilder Packages
        {
            get => new global::Soenneker.GitHub.OpenApiClient.User.Packages.PackagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The public_emails property</summary>
        public global::Soenneker.GitHub.OpenApiClient.User.Public_emails.Public_emailsRequestBuilder Public_emails
        {
            get => new global::Soenneker.GitHub.OpenApiClient.User.Public_emails.Public_emailsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The repos property</summary>
        public global::Soenneker.GitHub.OpenApiClient.User.Repos.ReposRequestBuilder Repos
        {
            get => new global::Soenneker.GitHub.OpenApiClient.User.Repos.ReposRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The repository_invitations property</summary>
        public global::Soenneker.GitHub.OpenApiClient.User.Repository_invitations.Repository_invitationsRequestBuilder Repository_invitations
        {
            get => new global::Soenneker.GitHub.OpenApiClient.User.Repository_invitations.Repository_invitationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The social_accounts property</summary>
        public global::Soenneker.GitHub.OpenApiClient.User.Social_accounts.Social_accountsRequestBuilder Social_accounts
        {
            get => new global::Soenneker.GitHub.OpenApiClient.User.Social_accounts.Social_accountsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ssh_signing_keys property</summary>
        public global::Soenneker.GitHub.OpenApiClient.User.Ssh_signing_keys.Ssh_signing_keysRequestBuilder Ssh_signing_keys
        {
            get => new global::Soenneker.GitHub.OpenApiClient.User.Ssh_signing_keys.Ssh_signing_keysRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The starred property</summary>
        public global::Soenneker.GitHub.OpenApiClient.User.Starred.StarredRequestBuilder Starred
        {
            get => new global::Soenneker.GitHub.OpenApiClient.User.Starred.StarredRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The subscriptions property</summary>
        public global::Soenneker.GitHub.OpenApiClient.User.Subscriptions.SubscriptionsRequestBuilder Subscriptions
        {
            get => new global::Soenneker.GitHub.OpenApiClient.User.Subscriptions.SubscriptionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The teams property</summary>
        public global::Soenneker.GitHub.OpenApiClient.User.Teams.TeamsRequestBuilder Teams
        {
            get => new global::Soenneker.GitHub.OpenApiClient.User.Teams.TeamsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.GitHub.OpenApiClient.user.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.GitHub.OpenApiClient.User.Item.AccountItemRequestBuilder"/></returns>
        public global::Soenneker.GitHub.OpenApiClient.User.Item.AccountItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("account%2Did", position);
                return new global::Soenneker.GitHub.OpenApiClient.User.Item.AccountItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitHub.OpenApiClient.User.UserRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UserRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/user", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitHub.OpenApiClient.User.UserRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UserRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/user", rawUrl)
        {
        }
        /// <summary>
        /// OAuth app tokens and personal access tokens (classic) need the `read:user` scope, or the broader `user` scope, for this endpoint to return the private user response. The private user response includes additional fields such as `private_gists`, `total_private_repos`, `owned_private_repos`, `disk_usage`, `collaborators`, and `two_factor_authentication`. Tokens without these scopes receive the public user response.The private and public user response types are unrelated to the [private profile](https://docs.github.com/account-and-profile/concepts/personal-profile#private-profiles) setting. A token without scopes still authenticates as the token&apos;s owner, so values subject to private profile visibility, such as `followers` and `following`, may differ from an unauthenticated response.
        /// API method documentation <see href="https://docs.github.com/rest/users/users#get-the-authenticated-user" />
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitHub.OpenApiClient.Models.UsersGetAuthenticated200Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.GitHub.OpenApiClient.Models.BasicError">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.GitHub.OpenApiClient.Models.BasicError">When receiving a 403 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.GitHub.OpenApiClient.Models.UsersGetAuthenticated200Response?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.GitHub.OpenApiClient.Models.UsersGetAuthenticated200Response> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Soenneker.GitHub.OpenApiClient.Models.BasicError.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.GitHub.OpenApiClient.Models.BasicError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.GitHub.OpenApiClient.Models.UsersGetAuthenticated200Response>(requestInfo, global::Soenneker.GitHub.OpenApiClient.Models.UsersGetAuthenticated200Response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// **Note:** If your email is set to private and you send an `email` parameter as part of this request to update your profile, your privacy settings are still enforced: the email address will not be displayed on your public profile or via the API.
        /// API method documentation <see href="https://docs.github.com/rest/users/users#update-the-authenticated-user" />
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitHub.OpenApiClient.Models.PrivateUser"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.GitHub.OpenApiClient.Models.BasicError">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.GitHub.OpenApiClient.Models.BasicError">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.GitHub.OpenApiClient.Models.BasicError">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.GitHub.OpenApiClient.Models.ValidationError">When receiving a 422 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.GitHub.OpenApiClient.Models.PrivateUser?> PatchAsync(global::Soenneker.GitHub.OpenApiClient.Models.UsersUpdateAuthenticatedRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.GitHub.OpenApiClient.Models.PrivateUser> PatchAsync(global::Soenneker.GitHub.OpenApiClient.Models.UsersUpdateAuthenticatedRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Soenneker.GitHub.OpenApiClient.Models.BasicError.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.GitHub.OpenApiClient.Models.BasicError.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.GitHub.OpenApiClient.Models.BasicError.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.GitHub.OpenApiClient.Models.ValidationError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.GitHub.OpenApiClient.Models.PrivateUser>(requestInfo, global::Soenneker.GitHub.OpenApiClient.Models.PrivateUser.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// OAuth app tokens and personal access tokens (classic) need the `read:user` scope, or the broader `user` scope, for this endpoint to return the private user response. The private user response includes additional fields such as `private_gists`, `total_private_repos`, `owned_private_repos`, `disk_usage`, `collaborators`, and `two_factor_authentication`. Tokens without these scopes receive the public user response.The private and public user response types are unrelated to the [private profile](https://docs.github.com/account-and-profile/concepts/personal-profile#private-profiles) setting. A token without scopes still authenticates as the token&apos;s owner, so values subject to private profile visibility, such as `followers` and `following`, may differ from an unauthenticated response.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// **Note:** If your email is set to private and you send an `email` parameter as part of this request to update your profile, your privacy settings are still enforced: the email address will not be displayed on your public profile or via the API.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::Soenneker.GitHub.OpenApiClient.Models.UsersUpdateAuthenticatedRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::Soenneker.GitHub.OpenApiClient.Models.UsersUpdateAuthenticatedRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitHub.OpenApiClient.User.UserRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.GitHub.OpenApiClient.User.UserRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.GitHub.OpenApiClient.User.UserRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
