// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitHub.OpenApiClient.Models
{
    /// <summary>The type of the source of the policy</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ActionsPolicySourceType
    {
        [EnumMember(Value = "Repository")]
        #pragma warning disable CS1591
        Repository,
        #pragma warning restore CS1591
        [EnumMember(Value = "Organization")]
        #pragma warning disable CS1591
        Organization,
        #pragma warning restore CS1591
        [EnumMember(Value = "Enterprise")]
        #pragma warning disable CS1591
        Enterprise,
        #pragma warning restore CS1591
    }
}
