// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitHub.OpenApiClient.Models
{
    /// <summary>The source of the runner image.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Actions_create_hosted_runner_for_org_image_source
    {
        [EnumMember(Value = "github")]
        #pragma warning disable CS1591
        Github,
        #pragma warning restore CS1591
        [EnumMember(Value = "partner")]
        #pragma warning disable CS1591
        Partner,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom")]
        #pragma warning disable CS1591
        Custom,
        #pragma warning restore CS1591
    }
}
