// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitHub.OpenApiClient.Models
{
    /// <summary>Billing unit used for this session. New sessions since June 1, 2026 use `ai_credits`, but older sessions use `premium_requests`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AgentTasksGetTaskByRepoAndId200ResponseSessionsItemUsageType
    {
        [EnumMember(Value = "ai_credits")]
        #pragma warning disable CS1591
        AiCredits,
        #pragma warning restore CS1591
        [EnumMember(Value = "premium_requests")]
        #pragma warning disable CS1591
        PremiumRequests,
        #pragma warning restore CS1591
    }
}
