// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitHub.OpenApiClient.Models
{
    /// <summary>How the author is associated with the repository.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AuthorAssociation
    {
        [EnumMember(Value = "COLLABORATOR")]
        #pragma warning disable CS1591
        Collaborator,
        #pragma warning restore CS1591
        [EnumMember(Value = "CONTRIBUTOR")]
        #pragma warning disable CS1591
        Contributor,
        #pragma warning restore CS1591
        [EnumMember(Value = "FIRST_TIMER")]
        #pragma warning disable CS1591
        FirstTimer,
        #pragma warning restore CS1591
        [EnumMember(Value = "FIRST_TIME_CONTRIBUTOR")]
        #pragma warning disable CS1591
        FirstTimeContributor,
        #pragma warning restore CS1591
        [EnumMember(Value = "MANNEQUIN")]
        #pragma warning disable CS1591
        Mannequin,
        #pragma warning restore CS1591
        [EnumMember(Value = "MEMBER")]
        #pragma warning disable CS1591
        Member,
        #pragma warning restore CS1591
        [EnumMember(Value = "NONE")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "OWNER")]
        #pragma warning disable CS1591
        Owner,
        #pragma warning restore CS1591
    }
}
