// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitHub.OpenApiClient.Models
{
    /// <summary>The scope of the budget</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BillingUpdateBudgetOrg_budget_scope
    {
        [EnumMember(Value = "enterprise")]
        #pragma warning disable CS1591
        Enterprise,
        #pragma warning restore CS1591
        [EnumMember(Value = "organization")]
        #pragma warning disable CS1591
        Organization,
        #pragma warning restore CS1591
        [EnumMember(Value = "repository")]
        #pragma warning disable CS1591
        Repository,
        #pragma warning restore CS1591
        [EnumMember(Value = "cost_center")]
        #pragma warning disable CS1591
        Cost_center,
        #pragma warning restore CS1591
    }
}
