// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.GitHub.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Budget : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The budget_alerting property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.BudgetBudgetAlerting? BudgetAlerting { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.BudgetBudgetAlerting BudgetAlerting { get; set; }
#endif
        /// <summary>The budget amount limit in whole dollars. For license-based products, this represents the number of licenses.</summary>
        public int? BudgetAmount { get; set; }
        /// <summary>The name of the entity for the budget (enterprise does not require a name).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BudgetEntityName { get; set; }
#nullable restore
#else
        public string BudgetEntityName { get; set; }
#endif
        /// <summary>A single product or sku to apply the budget to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BudgetProductSku { get; set; }
#nullable restore
#else
        public string BudgetProductSku { get; set; }
#endif
        /// <summary>The scope of the budget</summary>
        public global::Soenneker.GitHub.OpenApiClient.Models.BudgetBudgetScope? BudgetScope { get; set; }
        /// <summary>The type of pricing for the budget</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.BudgetBudgetType? BudgetType { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.BudgetBudgetType BudgetType { get; set; }
#endif
        /// <summary>The amount consumed for a user-scoped budget, or for a multi-user budget when filtering by user.</summary>
        public double? ConsumedAmount { get; set; }
        /// <summary>The date the budget will expire in `YYYY-MM-DD` format. Only dates in the future are accepted.If not provided, the budget will not expire.Only supported for budgets with `budget_scope` of `user`</summary>
        public Date? ExpiresAt { get; set; }
        /// <summary>The unique identifier for the budget</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The type of limit enforcement for the budget</summary>
        public bool? PreventFurtherUsage { get; set; }
        /// <summary>The user login when the budget is scoped to a single user (`user` scope).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? User { get; set; }
#nullable restore
#else
        public string User { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitHub.OpenApiClient.Models.Budget"/> and sets the default values.
        /// </summary>
        public Budget()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitHub.OpenApiClient.Models.Budget"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.GitHub.OpenApiClient.Models.Budget CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.GitHub.OpenApiClient.Models.Budget();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "budget_alerting", n => { BudgetAlerting = n.GetObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.BudgetBudgetAlerting>(global::Soenneker.GitHub.OpenApiClient.Models.BudgetBudgetAlerting.CreateFromDiscriminatorValue); } },
                { "budget_amount", n => { BudgetAmount = n.GetIntValue(); } },
                { "budget_entity_name", n => { BudgetEntityName = n.GetStringValue(); } },
                { "budget_product_sku", n => { BudgetProductSku = n.GetStringValue(); } },
                { "budget_scope", n => { BudgetScope = n.GetEnumValue<global::Soenneker.GitHub.OpenApiClient.Models.BudgetBudgetScope>(); } },
                { "budget_type", n => { BudgetType = n.GetObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.BudgetBudgetType>(global::Soenneker.GitHub.OpenApiClient.Models.BudgetBudgetType.CreateFromDiscriminatorValue); } },
                { "consumed_amount", n => { ConsumedAmount = n.GetDoubleValue(); } },
                { "expires_at", n => { ExpiresAt = n.GetDateValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "prevent_further_usage", n => { PreventFurtherUsage = n.GetBoolValue(); } },
                { "user", n => { User = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.BudgetBudgetAlerting>("budget_alerting", BudgetAlerting);
            writer.WriteIntValue("budget_amount", BudgetAmount);
            writer.WriteStringValue("budget_entity_name", BudgetEntityName);
            writer.WriteStringValue("budget_product_sku", BudgetProductSku);
            writer.WriteEnumValue<global::Soenneker.GitHub.OpenApiClient.Models.BudgetBudgetScope>("budget_scope", BudgetScope);
            writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.BudgetBudgetType>("budget_type", BudgetType);
            writer.WriteDoubleValue("consumed_amount", ConsumedAmount);
            writer.WriteDateValue("expires_at", ExpiresAt);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("prevent_further_usage", PreventFurtherUsage);
            writer.WriteStringValue("user", User);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
