// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitHub.OpenApiClient.Models
{
    /// <summary>The type of repositories to attach the configuration to.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Code_security_attach_enterprise_configuration_scope
    {
        [EnumMember(Value = "all")]
        #pragma warning disable CS1591
        All,
        #pragma warning restore CS1591
        [EnumMember(Value = "all_without_configurations")]
        #pragma warning disable CS1591
        All_without_configurations,
        #pragma warning restore CS1591
    }
}
