// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitHub.OpenApiClient.Models
{
    /// <summary>The reason for a failure of the variant analysis. This is only available if the variant analysis has failed.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CodeScanningVariantAnalysisFailureReason
    {
        [EnumMember(Value = "no_repos_queried")]
        #pragma warning disable CS1591
        NoReposQueried,
        #pragma warning restore CS1591
        [EnumMember(Value = "actions_workflow_run_failed")]
        #pragma warning disable CS1591
        ActionsWorkflowRunFailed,
        #pragma warning restore CS1591
        [EnumMember(Value = "internal_error")]
        #pragma warning disable CS1591
        InternalError,
        #pragma warning restore CS1591
    }
}
