// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitHub.OpenApiClient.Models
{
    /// <summary>The type of the bypass reviewer</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CodeSecurityUpdateConfigurationRequestSecretScanningDelegatedBypassOptionsReviewersItemReviewerType
    {
        [EnumMember(Value = "TEAM")]
        #pragma warning disable CS1591
        Team,
        #pragma warning restore CS1591
        [EnumMember(Value = "ROLE")]
        #pragma warning disable CS1591
        Role,
        #pragma warning restore CS1591
    }
}
