// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitHub.OpenApiClient.Models
{
    /// <summary>The policy state for Copilot coding agent in the enterprise. Can be one of `enabled_for_all_orgs`, `disabled_for_all_orgs`, `enabled_for_selected_orgs`, or `configured_by_org_admins`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CopilotSetEnterpriseCodingAgentPolicy_policy_state
    {
        [EnumMember(Value = "enabled_for_all_orgs")]
        #pragma warning disable CS1591
        Enabled_for_all_orgs,
        #pragma warning restore CS1591
        [EnumMember(Value = "disabled_for_all_orgs")]
        #pragma warning disable CS1591
        Disabled_for_all_orgs,
        #pragma warning restore CS1591
        [EnumMember(Value = "enabled_for_selected_orgs")]
        #pragma warning disable CS1591
        Enabled_for_selected_orgs,
        #pragma warning restore CS1591
        [EnumMember(Value = "configured_by_org_admins")]
        #pragma warning disable CS1591
        Configured_by_org_admins,
        #pragma warning restore CS1591
    }
}
