// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.GitHub.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.GitHub.OpenApiClient.Models.EnterpriseTeam"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.Team_1"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CopilotSeatDetailsAssigningTeam : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.EnterpriseTeam"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.EnterpriseTeam? EnterpriseTeam { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.EnterpriseTeam EnterpriseTeam { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.Team_1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.Team_1? Team1 { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.Team_1 Team1 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitHub.OpenApiClient.Models.CopilotSeatDetailsAssigningTeam"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.GitHub.OpenApiClient.Models.CopilotSeatDetailsAssigningTeam CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.GitHub.OpenApiClient.Models.CopilotSeatDetailsAssigningTeam();
            if("EnterpriseTeam".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.EnterpriseTeam = new global::Soenneker.GitHub.OpenApiClient.Models.EnterpriseTeam();
            }
            else if("Team_1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.Team1 = new global::Soenneker.GitHub.OpenApiClient.Models.Team_1();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(EnterpriseTeam != null)
            {
                return EnterpriseTeam.GetFieldDeserializers();
            }
            else if(Team1 != null)
            {
                return Team1.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(EnterpriseTeam != null)
            {
                writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.EnterpriseTeam>(null, EnterpriseTeam);
            }
            else if(Team1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.Team_1>(null, Team1);
            }
        }
    }
}
#pragma warning restore CS0618
