// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.GitHub.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CopilotSpacesAddCollaboratorForUser : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The username of the collaborator. The numeric user ID is also accepted.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ActorIdentifier { get; set; }
#nullable restore
#else
        public string ActorIdentifier { get; set; }
#endif
        /// <summary>The type of actor (must be `User` for user-owned spaces; `Team` will be rejected).</summary>
        public global::Soenneker.GitHub.OpenApiClient.Models.CopilotSpacesAddCollaboratorForUser_actor_type? ActorType { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The role to grant to the collaborator.</summary>
        public global::Soenneker.GitHub.OpenApiClient.Models.CopilotSpacesAddCollaboratorForUser_role? Role { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitHub.OpenApiClient.Models.CopilotSpacesAddCollaboratorForUser"/> and sets the default values.
        /// </summary>
        public CopilotSpacesAddCollaboratorForUser()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitHub.OpenApiClient.Models.CopilotSpacesAddCollaboratorForUser"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.GitHub.OpenApiClient.Models.CopilotSpacesAddCollaboratorForUser CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.GitHub.OpenApiClient.Models.CopilotSpacesAddCollaboratorForUser();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "actor_identifier", n => { ActorIdentifier = n.GetStringValue(); } },
                { "actor_type", n => { ActorType = n.GetEnumValue<global::Soenneker.GitHub.OpenApiClient.Models.CopilotSpacesAddCollaboratorForUser_actor_type>(); } },
                { "role", n => { Role = n.GetEnumValue<global::Soenneker.GitHub.OpenApiClient.Models.CopilotSpacesAddCollaboratorForUser_role>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("actor_identifier", ActorIdentifier);
            writer.WriteEnumValue<global::Soenneker.GitHub.OpenApiClient.Models.CopilotSpacesAddCollaboratorForUser_actor_type>("actor_type", ActorType);
            writer.WriteEnumValue<global::Soenneker.GitHub.OpenApiClient.Models.CopilotSpacesAddCollaboratorForUser_role>("role", Role);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
