// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitHub.OpenApiClient.Models
{
    /// <summary>&quot;The base role that determines default permissions.- `no_access`: No default access- `reader`: Default read permissions- `writer`: Default write permissions (organization spaces only)- `admin`: Default admin permissions (organization spaces only)&quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CopilotSpaceBaseRole
    {
        [EnumMember(Value = "reader")]
        #pragma warning disable CS1591
        Reader,
        #pragma warning restore CS1591
        [EnumMember(Value = "writer")]
        #pragma warning disable CS1591
        Writer,
        #pragma warning restore CS1591
        [EnumMember(Value = "admin")]
        #pragma warning disable CS1591
        Admin,
        #pragma warning restore CS1591
        [EnumMember(Value = "no_access")]
        #pragma warning disable CS1591
        NoAccess,
        #pragma warning restore CS1591
    }
}
