// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitHub.OpenApiClient.Models
{
    /// <summary>The base role that determines default permissions for the space.- `no_access`: No default access (default)- `reader`: Makes the space publicly readableNote: User spaces do not support writer or admin base roles.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CopilotSpacesCreateForUserRequestBaseRole
    {
        [EnumMember(Value = "reader")]
        #pragma warning disable CS1591
        Reader,
        #pragma warning restore CS1591
        [EnumMember(Value = "no_access")]
        #pragma warning disable CS1591
        NoAccess,
        #pragma warning restore CS1591
    }
}
