// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitHub.OpenApiClient.Models
{
    /// <summary>The type of the value for the property</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CustomPropertySetPayloadValueType
    {
        [EnumMember(Value = "string")]
        #pragma warning disable CS1591
        StringValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "single_select")]
        #pragma warning disable CS1591
        SingleSelect,
        #pragma warning restore CS1591
        [EnumMember(Value = "multi_select")]
        #pragma warning disable CS1591
        MultiSelect,
        #pragma warning restore CS1591
        [EnumMember(Value = "true_false")]
        #pragma warning disable CS1591
        TrueFalse,
        #pragma warning restore CS1591
        [EnumMember(Value = "url")]
        #pragma warning disable CS1591
        Url,
        #pragma warning restore CS1591
    }
}
