// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitHub.OpenApiClient.Models
{
    /// <summary>Whether team members will receive notifications when the team is mentioned.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EnterpriseTeamNotificationSetting
    {
        [EnumMember(Value = "notifications_enabled")]
        #pragma warning disable CS1591
        NotificationsEnabled,
        #pragma warning restore CS1591
        [EnumMember(Value = "notifications_disabled")]
        #pragma warning disable CS1591
        NotificationsDisabled,
        #pragma warning restore CS1591
    }
}
