// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.GitHub.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Enterprise_teams_update : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A new description for the team.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The ID of the IdP group to assign team membership with. The new IdP group will replace the existing one, or replace existing direct members if the team isn&apos;t currently linked to an IdP group.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GroupId { get; set; }
#nullable restore
#else
        public string GroupId { get; set; }
#endif
        /// <summary>A new name for the team.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>&quot;Specifies which organizations in the enterprise should have access to this team. Can be one of `disabled`, `selected`, or `all`.`disabled`: The team is not assigned to any organizations. This is the default when you create a new team.`selected`: The team is assigned to specific organizations. You can then use the [add organization assignments API](https://docs.github.com/rest/enterprise-teams/enterprise-team-organizations#add-organization-assignments).`all`: The team is assigned to all current and future organizations in the enterprise.&quot;</summary>
        public global::Soenneker.GitHub.OpenApiClient.Models.Enterprise_teams_update_organization_selection_type? OrganizationSelectionType { get; set; }
        /// <summary>&quot;Retired: this field is no longer supported.Whether the enterprise team should be reflected in each organization.This value cannot be changed.&quot;</summary>
        public global::Soenneker.GitHub.OpenApiClient.Models.Enterprise_teams_update_sync_to_organizations? SyncToOrganizations { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitHub.OpenApiClient.Models.Enterprise_teams_update"/> and sets the default values.
        /// </summary>
        public Enterprise_teams_update()
        {
            AdditionalData = new Dictionary<string, object>();
            OrganizationSelectionType = global::Soenneker.GitHub.OpenApiClient.Models.Enterprise_teams_update_organization_selection_type.Disabled;
            SyncToOrganizations = global::Soenneker.GitHub.OpenApiClient.Models.Enterprise_teams_update_sync_to_organizations.Disabled;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitHub.OpenApiClient.Models.Enterprise_teams_update"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.GitHub.OpenApiClient.Models.Enterprise_teams_update CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.GitHub.OpenApiClient.Models.Enterprise_teams_update();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "description", n => { Description = n.GetStringValue(); } },
                { "group_id", n => { GroupId = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "organization_selection_type", n => { OrganizationSelectionType = n.GetEnumValue<global::Soenneker.GitHub.OpenApiClient.Models.Enterprise_teams_update_organization_selection_type>(); } },
                { "sync_to_organizations", n => { SyncToOrganizations = n.GetEnumValue<global::Soenneker.GitHub.OpenApiClient.Models.Enterprise_teams_update_sync_to_organizations>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("group_id", GroupId);
            writer.WriteStringValue("name", Name);
            writer.WriteEnumValue<global::Soenneker.GitHub.OpenApiClient.Models.Enterprise_teams_update_organization_selection_type>("organization_selection_type", OrganizationSelectionType);
            writer.WriteEnumValue<global::Soenneker.GitHub.OpenApiClient.Models.Enterprise_teams_update_sync_to_organizations>("sync_to_organizations", SyncToOrganizations);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
