// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.GitHub.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.GitHub.OpenApiClient.Models.CommitCommentEvent"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.CreateEvent"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.DeleteEvent"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.DiscussionEvent"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.EventTypePayloadMember1"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.ForkEvent"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.GollumEvent"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.IssueCommentEvent"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.IssuesEvent"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.MemberEvent"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.PullRequestEvent"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.PullRequestReviewCommentEvent"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.PullRequestReviewEvent"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.PushEvent"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.ReleaseEvent"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.WatchEvent"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EventTypePayload : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.CommitCommentEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.CommitCommentEvent? CommitCommentEvent { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.CommitCommentEvent CommitCommentEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.CreateEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.CreateEvent? CreateEvent { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.CreateEvent CreateEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.DeleteEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.DeleteEvent? DeleteEvent { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.DeleteEvent DeleteEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.DiscussionEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.DiscussionEvent? DiscussionEvent { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.DiscussionEvent DiscussionEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.EventTypePayloadMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.EventTypePayloadMember1? EventTypePayloadMember1 { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.EventTypePayloadMember1 EventTypePayloadMember1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.ForkEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.ForkEvent? ForkEvent { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.ForkEvent ForkEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.GollumEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.GollumEvent? GollumEvent { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.GollumEvent GollumEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.IssueCommentEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.IssueCommentEvent? IssueCommentEvent { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.IssueCommentEvent IssueCommentEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.IssuesEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.IssuesEvent? IssuesEvent { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.IssuesEvent IssuesEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.MemberEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.MemberEvent? MemberEvent { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.MemberEvent MemberEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.PullRequestEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.PullRequestEvent? PullRequestEvent { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.PullRequestEvent PullRequestEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.PullRequestReviewCommentEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.PullRequestReviewCommentEvent? PullRequestReviewCommentEvent { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.PullRequestReviewCommentEvent PullRequestReviewCommentEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.PullRequestReviewEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.PullRequestReviewEvent? PullRequestReviewEvent { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.PullRequestReviewEvent PullRequestReviewEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.PushEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.PushEvent? PushEvent { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.PushEvent PushEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.ReleaseEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.ReleaseEvent? ReleaseEvent { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.ReleaseEvent ReleaseEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.WatchEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.WatchEvent? WatchEvent { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.WatchEvent WatchEvent { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitHub.OpenApiClient.Models.EventTypePayload"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.GitHub.OpenApiClient.Models.EventTypePayload CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.GitHub.OpenApiClient.Models.EventTypePayload();
            if("CommitCommentEvent".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CommitCommentEvent = new global::Soenneker.GitHub.OpenApiClient.Models.CommitCommentEvent();
            }
            else if("CreateEvent".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CreateEvent = new global::Soenneker.GitHub.OpenApiClient.Models.CreateEvent();
            }
            else if("DeleteEvent".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.DeleteEvent = new global::Soenneker.GitHub.OpenApiClient.Models.DeleteEvent();
            }
            else if("DiscussionEvent".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.DiscussionEvent = new global::Soenneker.GitHub.OpenApiClient.Models.DiscussionEvent();
            }
            else if("ForkEvent".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ForkEvent = new global::Soenneker.GitHub.OpenApiClient.Models.ForkEvent();
            }
            else if("GollumEvent".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.GollumEvent = new global::Soenneker.GitHub.OpenApiClient.Models.GollumEvent();
            }
            else if("IssueCommentEvent".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.IssueCommentEvent = new global::Soenneker.GitHub.OpenApiClient.Models.IssueCommentEvent();
            }
            else if("IssuesEvent".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.IssuesEvent = new global::Soenneker.GitHub.OpenApiClient.Models.IssuesEvent();
            }
            else if("MemberEvent".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.MemberEvent = new global::Soenneker.GitHub.OpenApiClient.Models.MemberEvent();
            }
            else if("PullRequestEvent".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.PullRequestEvent = new global::Soenneker.GitHub.OpenApiClient.Models.PullRequestEvent();
            }
            else if("PullRequestReviewCommentEvent".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.PullRequestReviewCommentEvent = new global::Soenneker.GitHub.OpenApiClient.Models.PullRequestReviewCommentEvent();
            }
            else if("PullRequestReviewEvent".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.PullRequestReviewEvent = new global::Soenneker.GitHub.OpenApiClient.Models.PullRequestReviewEvent();
            }
            else if("PushEvent".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.PushEvent = new global::Soenneker.GitHub.OpenApiClient.Models.PushEvent();
            }
            else if("ReleaseEvent".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ReleaseEvent = new global::Soenneker.GitHub.OpenApiClient.Models.ReleaseEvent();
            }
            else if("WatchEvent".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.WatchEvent = new global::Soenneker.GitHub.OpenApiClient.Models.WatchEvent();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(CommitCommentEvent != null)
            {
                return CommitCommentEvent.GetFieldDeserializers();
            }
            else if(CreateEvent != null)
            {
                return CreateEvent.GetFieldDeserializers();
            }
            else if(DeleteEvent != null)
            {
                return DeleteEvent.GetFieldDeserializers();
            }
            else if(DiscussionEvent != null)
            {
                return DiscussionEvent.GetFieldDeserializers();
            }
            else if(EventTypePayloadMember1 != null)
            {
                return EventTypePayloadMember1.GetFieldDeserializers();
            }
            else if(ForkEvent != null)
            {
                return ForkEvent.GetFieldDeserializers();
            }
            else if(GollumEvent != null)
            {
                return GollumEvent.GetFieldDeserializers();
            }
            else if(IssueCommentEvent != null)
            {
                return IssueCommentEvent.GetFieldDeserializers();
            }
            else if(IssuesEvent != null)
            {
                return IssuesEvent.GetFieldDeserializers();
            }
            else if(MemberEvent != null)
            {
                return MemberEvent.GetFieldDeserializers();
            }
            else if(PullRequestEvent != null)
            {
                return PullRequestEvent.GetFieldDeserializers();
            }
            else if(PullRequestReviewCommentEvent != null)
            {
                return PullRequestReviewCommentEvent.GetFieldDeserializers();
            }
            else if(PullRequestReviewEvent != null)
            {
                return PullRequestReviewEvent.GetFieldDeserializers();
            }
            else if(PushEvent != null)
            {
                return PushEvent.GetFieldDeserializers();
            }
            else if(ReleaseEvent != null)
            {
                return ReleaseEvent.GetFieldDeserializers();
            }
            else if(WatchEvent != null)
            {
                return WatchEvent.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(CommitCommentEvent != null)
            {
                writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.CommitCommentEvent>(null, CommitCommentEvent);
            }
            else if(CreateEvent != null)
            {
                writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.CreateEvent>(null, CreateEvent);
            }
            else if(DeleteEvent != null)
            {
                writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.DeleteEvent>(null, DeleteEvent);
            }
            else if(DiscussionEvent != null)
            {
                writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.DiscussionEvent>(null, DiscussionEvent);
            }
            else if(EventTypePayloadMember1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.EventTypePayloadMember1>(null, EventTypePayloadMember1);
            }
            else if(ForkEvent != null)
            {
                writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.ForkEvent>(null, ForkEvent);
            }
            else if(GollumEvent != null)
            {
                writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.GollumEvent>(null, GollumEvent);
            }
            else if(IssueCommentEvent != null)
            {
                writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.IssueCommentEvent>(null, IssueCommentEvent);
            }
            else if(IssuesEvent != null)
            {
                writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.IssuesEvent>(null, IssuesEvent);
            }
            else if(MemberEvent != null)
            {
                writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.MemberEvent>(null, MemberEvent);
            }
            else if(PullRequestEvent != null)
            {
                writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.PullRequestEvent>(null, PullRequestEvent);
            }
            else if(PullRequestReviewCommentEvent != null)
            {
                writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.PullRequestReviewCommentEvent>(null, PullRequestReviewCommentEvent);
            }
            else if(PullRequestReviewEvent != null)
            {
                writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.PullRequestReviewEvent>(null, PullRequestReviewEvent);
            }
            else if(PushEvent != null)
            {
                writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.PushEvent>(null, PushEvent);
            }
            else if(ReleaseEvent != null)
            {
                writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.ReleaseEvent>(null, ReleaseEvent);
            }
            else if(WatchEvent != null)
            {
                writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.WatchEvent>(null, WatchEvent);
            }
        }
    }
}
#pragma warning restore CS0618
