// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitHub.OpenApiClient.Models
{
    /// <summary>&quot;The policy controlling who can create pull requests: all or collaborators_only.&quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Fork_event_forkee_pull_request_creation_policy
    {
        [EnumMember(Value = "all")]
        #pragma warning disable CS1591
        All,
        #pragma warning restore CS1591
        [EnumMember(Value = "collaborators_only")]
        #pragma warning disable CS1591
        Collaborators_only,
        #pragma warning restore CS1591
    }
}
