// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitHub.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum IssuesListMilestonesSortParameter
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "due_on")]
        #pragma warning disable CS1591
        DueOn,
        #pragma warning restore CS1591
        [EnumMember(Value = "completeness")]
        #pragma warning disable CS1591
        Completeness,
        #pragma warning restore CS1591
    }
}
