// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.GitHub.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.GitHub.OpenApiClient.Models.IssuesSetLabelsRequestBranch2"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.IssuesSetLabelsRequestBranch4"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.IssuesSetLabelsRequestBranch5"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.IssuesSetLabelsRequestOneOf1"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.IssuesSetLabelsRequestOneOf3"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class IssuesSetLabelsRequest : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.IssuesSetLabelsRequestBranch2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.IssuesSetLabelsRequestBranch2? IssuesSetLabelsRequestBranch2 { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.IssuesSetLabelsRequestBranch2 IssuesSetLabelsRequestBranch2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.IssuesSetLabelsRequestBranch4"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.IssuesSetLabelsRequestBranch4? IssuesSetLabelsRequestBranch4 { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.IssuesSetLabelsRequestBranch4 IssuesSetLabelsRequestBranch4 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.IssuesSetLabelsRequestBranch5"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.IssuesSetLabelsRequestBranch5? IssuesSetLabelsRequestBranch5 { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.IssuesSetLabelsRequestBranch5 IssuesSetLabelsRequestBranch5 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.IssuesSetLabelsRequestOneOf1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.IssuesSetLabelsRequestOneOf1? IssuesSetLabelsRequestOneOf1 { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.IssuesSetLabelsRequestOneOf1 IssuesSetLabelsRequestOneOf1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.IssuesSetLabelsRequestOneOf3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.IssuesSetLabelsRequestOneOf3? IssuesSetLabelsRequestOneOf3 { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.IssuesSetLabelsRequestOneOf3 IssuesSetLabelsRequestOneOf3 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitHub.OpenApiClient.Models.IssuesSetLabelsRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.GitHub.OpenApiClient.Models.IssuesSetLabelsRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.GitHub.OpenApiClient.Models.IssuesSetLabelsRequest();
            if("IssuesSetLabelsRequestBranch2".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.IssuesSetLabelsRequestBranch2 = new global::Soenneker.GitHub.OpenApiClient.Models.IssuesSetLabelsRequestBranch2();
            }
            else if("IssuesSetLabelsRequestBranch4".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.IssuesSetLabelsRequestBranch4 = new global::Soenneker.GitHub.OpenApiClient.Models.IssuesSetLabelsRequestBranch4();
            }
            else if("IssuesSetLabelsRequestBranch5".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.IssuesSetLabelsRequestBranch5 = new global::Soenneker.GitHub.OpenApiClient.Models.IssuesSetLabelsRequestBranch5();
            }
            else if("IssuesSetLabelsRequestOneOf1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.IssuesSetLabelsRequestOneOf1 = new global::Soenneker.GitHub.OpenApiClient.Models.IssuesSetLabelsRequestOneOf1();
            }
            else if("IssuesSetLabelsRequestOneOf3".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.IssuesSetLabelsRequestOneOf3 = new global::Soenneker.GitHub.OpenApiClient.Models.IssuesSetLabelsRequestOneOf3();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(IssuesSetLabelsRequestBranch2 != null)
            {
                return IssuesSetLabelsRequestBranch2.GetFieldDeserializers();
            }
            else if(IssuesSetLabelsRequestBranch4 != null)
            {
                return IssuesSetLabelsRequestBranch4.GetFieldDeserializers();
            }
            else if(IssuesSetLabelsRequestBranch5 != null)
            {
                return IssuesSetLabelsRequestBranch5.GetFieldDeserializers();
            }
            else if(IssuesSetLabelsRequestOneOf1 != null)
            {
                return IssuesSetLabelsRequestOneOf1.GetFieldDeserializers();
            }
            else if(IssuesSetLabelsRequestOneOf3 != null)
            {
                return IssuesSetLabelsRequestOneOf3.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(IssuesSetLabelsRequestBranch2 != null)
            {
                writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.IssuesSetLabelsRequestBranch2>(null, IssuesSetLabelsRequestBranch2);
            }
            else if(IssuesSetLabelsRequestBranch4 != null)
            {
                writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.IssuesSetLabelsRequestBranch4>(null, IssuesSetLabelsRequestBranch4);
            }
            else if(IssuesSetLabelsRequestBranch5 != null)
            {
                writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.IssuesSetLabelsRequestBranch5>(null, IssuesSetLabelsRequestBranch5);
            }
            else if(IssuesSetLabelsRequestOneOf1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.IssuesSetLabelsRequestOneOf1>(null, IssuesSetLabelsRequestOneOf1);
            }
            else if(IssuesSetLabelsRequestOneOf3 != null)
            {
                writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.IssuesSetLabelsRequestOneOf3>(null, IssuesSetLabelsRequestOneOf3);
            }
        }
    }
}
#pragma warning restore CS0618
