// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.GitHub.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.GitHub.OpenApiClient.Models.IssuesAddLabelsRequestBranch2"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.IssuesAddLabelsRequestBranch3"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.IssuesAddLabelsRequestOneOf1"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class IssuesAddLabelsRequest : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.IssuesAddLabelsRequestBranch2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.IssuesAddLabelsRequestBranch2? IssuesAddLabelsRequestBranch2 { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.IssuesAddLabelsRequestBranch2 IssuesAddLabelsRequestBranch2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.IssuesAddLabelsRequestBranch3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.IssuesAddLabelsRequestBranch3? IssuesAddLabelsRequestBranch3 { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.IssuesAddLabelsRequestBranch3 IssuesAddLabelsRequestBranch3 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.IssuesAddLabelsRequestOneOf1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.IssuesAddLabelsRequestOneOf1? IssuesAddLabelsRequestOneOf1 { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.IssuesAddLabelsRequestOneOf1 IssuesAddLabelsRequestOneOf1 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitHub.OpenApiClient.Models.IssuesAddLabelsRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.GitHub.OpenApiClient.Models.IssuesAddLabelsRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.GitHub.OpenApiClient.Models.IssuesAddLabelsRequest();
            if("IssuesAddLabelsRequest_2".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.IssuesAddLabelsRequestBranch2 = new global::Soenneker.GitHub.OpenApiClient.Models.IssuesAddLabelsRequestBranch2();
            }
            else if("IssuesAddLabelsRequest_3".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.IssuesAddLabelsRequestBranch3 = new global::Soenneker.GitHub.OpenApiClient.Models.IssuesAddLabelsRequestBranch3();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(IssuesAddLabelsRequestBranch2 != null)
            {
                return IssuesAddLabelsRequestBranch2.GetFieldDeserializers();
            }
            else if(IssuesAddLabelsRequestBranch3 != null)
            {
                return IssuesAddLabelsRequestBranch3.GetFieldDeserializers();
            }
            else if(IssuesAddLabelsRequestOneOf1 != null)
            {
                return IssuesAddLabelsRequestOneOf1.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(IssuesAddLabelsRequestBranch2 != null)
            {
                writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.IssuesAddLabelsRequestBranch2>(null, IssuesAddLabelsRequestBranch2);
            }
            else if(IssuesAddLabelsRequestBranch3 != null)
            {
                writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.IssuesAddLabelsRequestBranch3>(null, IssuesAddLabelsRequestBranch3);
            }
            else if(IssuesAddLabelsRequestOneOf1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.IssuesAddLabelsRequestOneOf1>(null, IssuesAddLabelsRequestOneOf1);
            }
        }
    }
}
#pragma warning restore CS0618
