// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitHub.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum IssuesUpdate200ResponseSuggestionsAssigneesItemIgnoredReason
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "already_applied")]
        #pragma warning disable CS1591
        AlreadyApplied,
        #pragma warning restore CS1591
        [EnumMember(Value = "issue_already_closed")]
        #pragma warning disable CS1591
        IssueAlreadyClosed,
        #pragma warning restore CS1591
    }
}
