// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitHub.OpenApiClient.Models
{
    /// <summary>Action to apply to the requests.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Orgs_review_pat_grant_requests_in_bulk_action
    {
        [EnumMember(Value = "approve")]
        #pragma warning disable CS1591
        Approve,
        #pragma warning restore CS1591
        [EnumMember(Value = "deny")]
        #pragma warning disable CS1591
        Deny,
        #pragma warning restore CS1591
    }
}
