// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.GitHub.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.GitHub.OpenApiClient.Models.ProjectsAddFieldForOrgRequestOneOf1"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.ProjectsAddFieldForOrgRequestOneOf2"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.ProjectsAddFieldForOrgRequestOneOf3"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.ProjectsAddFieldForOrgRequestOneOf4"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProjectsAddFieldForOrgRequest : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.ProjectsAddFieldForOrgRequestOneOf1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.ProjectsAddFieldForOrgRequestOneOf1? ProjectsAddFieldForOrgRequestOneOf1 { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.ProjectsAddFieldForOrgRequestOneOf1 ProjectsAddFieldForOrgRequestOneOf1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.ProjectsAddFieldForOrgRequestOneOf2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.ProjectsAddFieldForOrgRequestOneOf2? ProjectsAddFieldForOrgRequestOneOf2 { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.ProjectsAddFieldForOrgRequestOneOf2 ProjectsAddFieldForOrgRequestOneOf2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.ProjectsAddFieldForOrgRequestOneOf3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.ProjectsAddFieldForOrgRequestOneOf3? ProjectsAddFieldForOrgRequestOneOf3 { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.ProjectsAddFieldForOrgRequestOneOf3 ProjectsAddFieldForOrgRequestOneOf3 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.ProjectsAddFieldForOrgRequestOneOf4"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.ProjectsAddFieldForOrgRequestOneOf4? ProjectsAddFieldForOrgRequestOneOf4 { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.ProjectsAddFieldForOrgRequestOneOf4 ProjectsAddFieldForOrgRequestOneOf4 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitHub.OpenApiClient.Models.ProjectsAddFieldForOrgRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.GitHub.OpenApiClient.Models.ProjectsAddFieldForOrgRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.GitHub.OpenApiClient.Models.ProjectsAddFieldForOrgRequest();
            if("ProjectsAddFieldForOrgRequestOneOf1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ProjectsAddFieldForOrgRequestOneOf1 = new global::Soenneker.GitHub.OpenApiClient.Models.ProjectsAddFieldForOrgRequestOneOf1();
            }
            else if("ProjectsAddFieldForOrgRequestOneOf2".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ProjectsAddFieldForOrgRequestOneOf2 = new global::Soenneker.GitHub.OpenApiClient.Models.ProjectsAddFieldForOrgRequestOneOf2();
            }
            else if("ProjectsAddFieldForOrgRequestOneOf3".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ProjectsAddFieldForOrgRequestOneOf3 = new global::Soenneker.GitHub.OpenApiClient.Models.ProjectsAddFieldForOrgRequestOneOf3();
            }
            else if("ProjectsAddFieldForOrgRequestOneOf4".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ProjectsAddFieldForOrgRequestOneOf4 = new global::Soenneker.GitHub.OpenApiClient.Models.ProjectsAddFieldForOrgRequestOneOf4();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(ProjectsAddFieldForOrgRequestOneOf1 != null)
            {
                return ProjectsAddFieldForOrgRequestOneOf1.GetFieldDeserializers();
            }
            else if(ProjectsAddFieldForOrgRequestOneOf2 != null)
            {
                return ProjectsAddFieldForOrgRequestOneOf2.GetFieldDeserializers();
            }
            else if(ProjectsAddFieldForOrgRequestOneOf3 != null)
            {
                return ProjectsAddFieldForOrgRequestOneOf3.GetFieldDeserializers();
            }
            else if(ProjectsAddFieldForOrgRequestOneOf4 != null)
            {
                return ProjectsAddFieldForOrgRequestOneOf4.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(ProjectsAddFieldForOrgRequestOneOf1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.ProjectsAddFieldForOrgRequestOneOf1>(null, ProjectsAddFieldForOrgRequestOneOf1);
            }
            else if(ProjectsAddFieldForOrgRequestOneOf2 != null)
            {
                writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.ProjectsAddFieldForOrgRequestOneOf2>(null, ProjectsAddFieldForOrgRequestOneOf2);
            }
            else if(ProjectsAddFieldForOrgRequestOneOf3 != null)
            {
                writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.ProjectsAddFieldForOrgRequestOneOf3>(null, ProjectsAddFieldForOrgRequestOneOf3);
            }
            else if(ProjectsAddFieldForOrgRequestOneOf4 != null)
            {
                writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.ProjectsAddFieldForOrgRequestOneOf4>(null, ProjectsAddFieldForOrgRequestOneOf4);
            }
        }
    }
}
#pragma warning restore CS0618
