// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.GitHub.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.GitHub.OpenApiClient.Models.Issue"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.ProjectsV2DraftIssue"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.PullRequestSimple"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProjectsV2ItemSimpleContent : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.Issue"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.Issue? Issue { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.Issue Issue { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.ProjectsV2DraftIssue"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.ProjectsV2DraftIssue? ProjectsV2DraftIssue { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.ProjectsV2DraftIssue ProjectsV2DraftIssue { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.PullRequestSimple"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.PullRequestSimple? PullRequestSimple { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.PullRequestSimple PullRequestSimple { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitHub.OpenApiClient.Models.ProjectsV2ItemSimpleContent"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.GitHub.OpenApiClient.Models.ProjectsV2ItemSimpleContent CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.GitHub.OpenApiClient.Models.ProjectsV2ItemSimpleContent();
            if("Issue".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.Issue = new global::Soenneker.GitHub.OpenApiClient.Models.Issue();
            }
            else if("ProjectsV2DraftIssue".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ProjectsV2DraftIssue = new global::Soenneker.GitHub.OpenApiClient.Models.ProjectsV2DraftIssue();
            }
            else if("PullRequestSimple".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.PullRequestSimple = new global::Soenneker.GitHub.OpenApiClient.Models.PullRequestSimple();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(Issue != null)
            {
                return Issue.GetFieldDeserializers();
            }
            else if(ProjectsV2DraftIssue != null)
            {
                return ProjectsV2DraftIssue.GetFieldDeserializers();
            }
            else if(PullRequestSimple != null)
            {
                return PullRequestSimple.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(Issue != null)
            {
                writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.Issue>(null, Issue);
            }
            else if(ProjectsV2DraftIssue != null)
            {
                writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.ProjectsV2DraftIssue>(null, ProjectsV2DraftIssue);
            }
            else if(PullRequestSimple != null)
            {
                writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.PullRequestSimple>(null, PullRequestSimple);
            }
        }
    }
}
#pragma warning restore CS0618
