// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitHub.OpenApiClient.Models
{
    /// <summary>The field&apos;s data type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ProjectsAddFieldForUserRequestDataType
    {
        [EnumMember(Value = "text")]
        #pragma warning disable CS1591
        Text,
        #pragma warning restore CS1591
        [EnumMember(Value = "number")]
        #pragma warning disable CS1591
        Number,
        #pragma warning restore CS1591
        [EnumMember(Value = "date")]
        #pragma warning disable CS1591
        Date,
        #pragma warning restore CS1591
        [EnumMember(Value = "single_select")]
        #pragma warning disable CS1591
        SingleSelect,
        #pragma warning restore CS1591
        [EnumMember(Value = "iteration")]
        #pragma warning disable CS1591
        Iteration,
        #pragma warning restore CS1591
    }
}
