// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.GitHub.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.GitHub.OpenApiClient.Models.PullRequestMergeAsyncResultDetailsOneOf1"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.PullRequestMergeAsyncResultDetailsOneOf2"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.PullRequestMergeAsyncResultDetailsOneOf3"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PullRequestMergeAsyncResultDetails : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.PullRequestMergeAsyncResultDetailsOneOf1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.PullRequestMergeAsyncResultDetailsOneOf1? PullRequestMergeAsyncResultDetailsOneOf1 { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.PullRequestMergeAsyncResultDetailsOneOf1 PullRequestMergeAsyncResultDetailsOneOf1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.PullRequestMergeAsyncResultDetailsOneOf2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.PullRequestMergeAsyncResultDetailsOneOf2? PullRequestMergeAsyncResultDetailsOneOf2 { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.PullRequestMergeAsyncResultDetailsOneOf2 PullRequestMergeAsyncResultDetailsOneOf2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.PullRequestMergeAsyncResultDetailsOneOf3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.PullRequestMergeAsyncResultDetailsOneOf3? PullRequestMergeAsyncResultDetailsOneOf3 { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.PullRequestMergeAsyncResultDetailsOneOf3 PullRequestMergeAsyncResultDetailsOneOf3 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitHub.OpenApiClient.Models.PullRequestMergeAsyncResultDetails"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.GitHub.OpenApiClient.Models.PullRequestMergeAsyncResultDetails CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.GitHub.OpenApiClient.Models.PullRequestMergeAsyncResultDetails();
            if("PullRequestMergeAsyncResultDetailsOneOf1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.PullRequestMergeAsyncResultDetailsOneOf1 = new global::Soenneker.GitHub.OpenApiClient.Models.PullRequestMergeAsyncResultDetailsOneOf1();
            }
            else if("PullRequestMergeAsyncResultDetailsOneOf2".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.PullRequestMergeAsyncResultDetailsOneOf2 = new global::Soenneker.GitHub.OpenApiClient.Models.PullRequestMergeAsyncResultDetailsOneOf2();
            }
            else if("PullRequestMergeAsyncResultDetailsOneOf3".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.PullRequestMergeAsyncResultDetailsOneOf3 = new global::Soenneker.GitHub.OpenApiClient.Models.PullRequestMergeAsyncResultDetailsOneOf3();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(PullRequestMergeAsyncResultDetailsOneOf1 != null)
            {
                return PullRequestMergeAsyncResultDetailsOneOf1.GetFieldDeserializers();
            }
            else if(PullRequestMergeAsyncResultDetailsOneOf2 != null)
            {
                return PullRequestMergeAsyncResultDetailsOneOf2.GetFieldDeserializers();
            }
            else if(PullRequestMergeAsyncResultDetailsOneOf3 != null)
            {
                return PullRequestMergeAsyncResultDetailsOneOf3.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(PullRequestMergeAsyncResultDetailsOneOf1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.PullRequestMergeAsyncResultDetailsOneOf1>(null, PullRequestMergeAsyncResultDetailsOneOf1);
            }
            else if(PullRequestMergeAsyncResultDetailsOneOf2 != null)
            {
                writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.PullRequestMergeAsyncResultDetailsOneOf2>(null, PullRequestMergeAsyncResultDetailsOneOf2);
            }
            else if(PullRequestMergeAsyncResultDetailsOneOf3 != null)
            {
                writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.PullRequestMergeAsyncResultDetailsOneOf3>(null, PullRequestMergeAsyncResultDetailsOneOf3);
            }
        }
    }
}
#pragma warning restore CS0618
