// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.GitHub.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PullRequestStackMinimalPullRequestsItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The draft property</summary>
        public bool? Draft { get; set; }
        /// <summary>The head property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.PullRequestStackMinimalPullRequestsItemHead? Head { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.PullRequestStackMinimalPullRequestsItemHead Head { get; set; }
#endif
        /// <summary>The merged_at property</summary>
        public DateTimeOffset? MergedAt { get; set; }
        /// <summary>The number property</summary>
        public int? Number { get; set; }
        /// <summary>The state property</summary>
        public global::Soenneker.GitHub.OpenApiClient.Models.PullRequestStackMinimalPullRequestsItemState? State { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitHub.OpenApiClient.Models.PullRequestStackMinimalPullRequestsItem"/> and sets the default values.
        /// </summary>
        public PullRequestStackMinimalPullRequestsItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitHub.OpenApiClient.Models.PullRequestStackMinimalPullRequestsItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.GitHub.OpenApiClient.Models.PullRequestStackMinimalPullRequestsItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.GitHub.OpenApiClient.Models.PullRequestStackMinimalPullRequestsItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "draft", n => { Draft = n.GetBoolValue(); } },
                { "head", n => { Head = n.GetObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.PullRequestStackMinimalPullRequestsItemHead>(global::Soenneker.GitHub.OpenApiClient.Models.PullRequestStackMinimalPullRequestsItemHead.CreateFromDiscriminatorValue); } },
                { "merged_at", n => { MergedAt = n.GetDateTimeOffsetValue(); } },
                { "number", n => { Number = n.GetIntValue(); } },
                { "state", n => { State = n.GetEnumValue<global::Soenneker.GitHub.OpenApiClient.Models.PullRequestStackMinimalPullRequestsItemState>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("draft", Draft);
            writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.PullRequestStackMinimalPullRequestsItemHead>("head", Head);
            writer.WriteDateTimeOffsetValue("merged_at", MergedAt);
            writer.WriteIntValue("number", Number);
            writer.WriteEnumValue<global::Soenneker.GitHub.OpenApiClient.Models.PullRequestStackMinimalPullRequestsItemState>("state", State);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
