// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitHub.OpenApiClient.Models
{
    /// <summary>The repository directory that includes the source files for the Pages site. Allowed paths are `/` or `/docs`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Repos_update_information_about_pages_site_sourceMember1_path
    {
        [EnumMember(Value = "/")]
        #pragma warning disable CS1591
        Slash,
        #pragma warning restore CS1591
        [EnumMember(Value = "/docs")]
        #pragma warning disable CS1591
        Docs,
        #pragma warning restore CS1591
    }
}
