// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitHub.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum RepositoryRuleFileExtensionRestrictionType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "file_extension_restriction")]
        #pragma warning disable CS1591
        FileExtensionRestriction,
        #pragma warning restore CS1591
    }
}
