// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.GitHub.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.GitHub.OpenApiClient.Models.ReposRemoveTeamAccessRestrictionsRequestBranch2"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.ReposRemoveTeamAccessRestrictionsRequestOneOf1"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ReposRemoveTeamAccessRestrictionsRequest : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.ReposRemoveTeamAccessRestrictionsRequestBranch2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.ReposRemoveTeamAccessRestrictionsRequestBranch2? ReposRemoveTeamAccessRestrictionsRequestBranch2 { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.ReposRemoveTeamAccessRestrictionsRequestBranch2 ReposRemoveTeamAccessRestrictionsRequestBranch2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.ReposRemoveTeamAccessRestrictionsRequestOneOf1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.ReposRemoveTeamAccessRestrictionsRequestOneOf1? ReposRemoveTeamAccessRestrictionsRequestOneOf1 { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.ReposRemoveTeamAccessRestrictionsRequestOneOf1 ReposRemoveTeamAccessRestrictionsRequestOneOf1 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitHub.OpenApiClient.Models.ReposRemoveTeamAccessRestrictionsRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.GitHub.OpenApiClient.Models.ReposRemoveTeamAccessRestrictionsRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.GitHub.OpenApiClient.Models.ReposRemoveTeamAccessRestrictionsRequest();
            if("ReposRemoveTeamAccessRestrictionsRequest_2".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ReposRemoveTeamAccessRestrictionsRequestBranch2 = new global::Soenneker.GitHub.OpenApiClient.Models.ReposRemoveTeamAccessRestrictionsRequestBranch2();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(ReposRemoveTeamAccessRestrictionsRequestBranch2 != null)
            {
                return ReposRemoveTeamAccessRestrictionsRequestBranch2.GetFieldDeserializers();
            }
            else if(ReposRemoveTeamAccessRestrictionsRequestOneOf1 != null)
            {
                return ReposRemoveTeamAccessRestrictionsRequestOneOf1.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(ReposRemoveTeamAccessRestrictionsRequestBranch2 != null)
            {
                writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.ReposRemoveTeamAccessRestrictionsRequestBranch2>(null, ReposRemoveTeamAccessRestrictionsRequestBranch2);
            }
            else if(ReposRemoveTeamAccessRestrictionsRequestOneOf1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.ReposRemoveTeamAccessRestrictionsRequestOneOf1>(null, ReposRemoveTeamAccessRestrictionsRequestOneOf1);
            }
        }
    }
}
#pragma warning restore CS0618
