// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.GitHub.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.GitHub.OpenApiClient.Models.Content_directory_Wrapper"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.Content_file"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.Content_submodule"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.Content_symlink"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Repos_get_content_200 : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.Content_directory_Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.Content_directory_Wrapper? ContentDirectoryWrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.Content_directory_Wrapper ContentDirectoryWrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.Content_file"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.Content_file? ContentFile { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.Content_file ContentFile { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.Content_submodule"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.Content_submodule? ContentSubmodule { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.Content_submodule ContentSubmodule { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.Content_symlink"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.Content_symlink? ContentSymlink { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.Content_symlink ContentSymlink { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitHub.OpenApiClient.Models.Repos_get_content_200"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.GitHub.OpenApiClient.Models.Repos_get_content_200 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.GitHub.OpenApiClient.Models.Repos_get_content_200();
            if("content_directory".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ContentDirectoryWrapper = new global::Soenneker.GitHub.OpenApiClient.Models.Content_directory_Wrapper();
            }
            else if("content_file".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ContentFile = new global::Soenneker.GitHub.OpenApiClient.Models.Content_file();
            }
            else if("content_submodule".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ContentSubmodule = new global::Soenneker.GitHub.OpenApiClient.Models.Content_submodule();
            }
            else if("content_symlink".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ContentSymlink = new global::Soenneker.GitHub.OpenApiClient.Models.Content_symlink();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(ContentDirectoryWrapper != null)
            {
                return ContentDirectoryWrapper.GetFieldDeserializers();
            }
            else if(ContentFile != null)
            {
                return ContentFile.GetFieldDeserializers();
            }
            else if(ContentSubmodule != null)
            {
                return ContentSubmodule.GetFieldDeserializers();
            }
            else if(ContentSymlink != null)
            {
                return ContentSymlink.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(ContentDirectoryWrapper != null)
            {
                writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.Content_directory_Wrapper>(null, ContentDirectoryWrapper);
            }
            else if(ContentFile != null)
            {
                writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.Content_file>(null, ContentFile);
            }
            else if(ContentSubmodule != null)
            {
                writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.Content_submodule>(null, ContentSubmodule);
            }
            else if(ContentSymlink != null)
            {
                writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.Content_symlink>(null, ContentSymlink);
            }
        }
    }
}
#pragma warning restore CS0618
