// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitHub.OpenApiClient.Models
{
    /// <summary>The process by which the GitHub Pages site will be built. `workflow` means that the site is built by a custom GitHub Actions workflow. `legacy` means that the site is built by GitHub when changes are pushed to a specific branch.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Repos_update_information_about_pages_site_build_type
    {
        [EnumMember(Value = "legacy")]
        #pragma warning disable CS1591
        Legacy,
        #pragma warning restore CS1591
        [EnumMember(Value = "workflow")]
        #pragma warning disable CS1591
        Workflow,
        #pragma warning restore CS1591
    }
}
