// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitHub.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SearchUsersSortParameter
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "followers")]
        #pragma warning disable CS1591
        Followers,
        #pragma warning restore CS1591
        [EnumMember(Value = "repositories")]
        #pragma warning disable CS1591
        Repositories,
        #pragma warning restore CS1591
        [EnumMember(Value = "joined")]
        #pragma warning disable CS1591
        Joined,
        #pragma warning restore CS1591
    }
}
