// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitHub.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SearchIssuesAndPullRequests200ResponseLexicalFallbackReasonItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "no_text_terms")]
        #pragma warning disable CS1591
        NoTextTerms,
        #pragma warning restore CS1591
        [EnumMember(Value = "quoted_text")]
        #pragma warning disable CS1591
        QuotedText,
        #pragma warning restore CS1591
        [EnumMember(Value = "non_issue_target")]
        #pragma warning disable CS1591
        NonIssueTarget,
        #pragma warning restore CS1591
        [EnumMember(Value = "or_boolean_not_supported")]
        #pragma warning disable CS1591
        OrBooleanNotSupported,
        #pragma warning restore CS1591
        [EnumMember(Value = "no_accessible_repos")]
        #pragma warning disable CS1591
        NoAccessibleRepos,
        #pragma warning restore CS1591
        [EnumMember(Value = "server_error")]
        #pragma warning disable CS1591
        ServerError,
        #pragma warning restore CS1591
        [EnumMember(Value = "only_non_semantic_fields_requested")]
        #pragma warning disable CS1591
        OnlyNonSemanticFieldsRequested,
        #pragma warning restore CS1591
        [EnumMember(Value = "service_unavailable")]
        #pragma warning disable CS1591
        ServiceUnavailable,
        #pragma warning restore CS1591
    }
}
