// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitHub.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum WorkflowsType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "workflows")]
        #pragma warning disable CS1591
        Workflows,
        #pragma warning restore CS1591
    }
}
