// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.GitHub.OpenApiClient.Repos.Item.Item.CodeQuality.Findings;
using Soenneker.GitHub.OpenApiClient.Repos.Item.Item.CodeQuality.Setup;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.GitHub.OpenApiClient.Repos.Item.Item.CodeQuality
{
    /// <summary>
    /// Builds and executes requests for operations under \repos\{owner-id}\{repo-id}\code-quality
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CodeQualityRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The findings property</summary>
        public global::Soenneker.GitHub.OpenApiClient.Repos.Item.Item.CodeQuality.Findings.FindingsRequestBuilder Findings
        {
            get => new global::Soenneker.GitHub.OpenApiClient.Repos.Item.Item.CodeQuality.Findings.FindingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The setup property</summary>
        public global::Soenneker.GitHub.OpenApiClient.Repos.Item.Item.CodeQuality.Setup.SetupRequestBuilder Setup
        {
            get => new global::Soenneker.GitHub.OpenApiClient.Repos.Item.Item.CodeQuality.Setup.SetupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitHub.OpenApiClient.Repos.Item.Item.CodeQuality.CodeQualityRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CodeQualityRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/repos/{owner%2Did}/{repo%2Did}/code-quality", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitHub.OpenApiClient.Repos.Item.Item.CodeQuality.CodeQualityRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CodeQualityRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/repos/{owner%2Did}/{repo%2Did}/code-quality", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
