// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.GitHub.OpenApiClient.Models;
using Soenneker.GitHub.OpenApiClient.Users.Item.Attestations;
using Soenneker.GitHub.OpenApiClient.Users.Item.CopilotSpaces;
using Soenneker.GitHub.OpenApiClient.Users.Item.Docker;
using Soenneker.GitHub.OpenApiClient.Users.Item.Events;
using Soenneker.GitHub.OpenApiClient.Users.Item.Followers;
using Soenneker.GitHub.OpenApiClient.Users.Item.Following;
using Soenneker.GitHub.OpenApiClient.Users.Item.Gists;
using Soenneker.GitHub.OpenApiClient.Users.Item.Gpg_keys;
using Soenneker.GitHub.OpenApiClient.Users.Item.Hovercard;
using Soenneker.GitHub.OpenApiClient.Users.Item.Installation;
using Soenneker.GitHub.OpenApiClient.Users.Item.Keys;
using Soenneker.GitHub.OpenApiClient.Users.Item.Orgs;
using Soenneker.GitHub.OpenApiClient.Users.Item.Packages;
using Soenneker.GitHub.OpenApiClient.Users.Item.ProjectsV2;
using Soenneker.GitHub.OpenApiClient.Users.Item.Received_events;
using Soenneker.GitHub.OpenApiClient.Users.Item.Repos;
using Soenneker.GitHub.OpenApiClient.Users.Item.Settings;
using Soenneker.GitHub.OpenApiClient.Users.Item.Social_accounts;
using Soenneker.GitHub.OpenApiClient.Users.Item.Ssh_signing_keys;
using Soenneker.GitHub.OpenApiClient.Users.Item.Starred;
using Soenneker.GitHub.OpenApiClient.Users.Item.Subscriptions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.GitHub.OpenApiClient.Users.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \users\{user-id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UserItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The attestations property</summary>
        public global::Soenneker.GitHub.OpenApiClient.Users.Item.Attestations.AttestationsRequestBuilder Attestations
        {
            get => new global::Soenneker.GitHub.OpenApiClient.Users.Item.Attestations.AttestationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The copilotSpaces property</summary>
        public global::Soenneker.GitHub.OpenApiClient.Users.Item.CopilotSpaces.CopilotSpacesRequestBuilder CopilotSpaces
        {
            get => new global::Soenneker.GitHub.OpenApiClient.Users.Item.CopilotSpaces.CopilotSpacesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The docker property</summary>
        public global::Soenneker.GitHub.OpenApiClient.Users.Item.Docker.DockerRequestBuilder Docker
        {
            get => new global::Soenneker.GitHub.OpenApiClient.Users.Item.Docker.DockerRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The events property</summary>
        public global::Soenneker.GitHub.OpenApiClient.Users.Item.Events.EventsRequestBuilder Events
        {
            get => new global::Soenneker.GitHub.OpenApiClient.Users.Item.Events.EventsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The followers property</summary>
        public global::Soenneker.GitHub.OpenApiClient.Users.Item.Followers.FollowersRequestBuilder Followers
        {
            get => new global::Soenneker.GitHub.OpenApiClient.Users.Item.Followers.FollowersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The following property</summary>
        public global::Soenneker.GitHub.OpenApiClient.Users.Item.Following.FollowingRequestBuilder Following
        {
            get => new global::Soenneker.GitHub.OpenApiClient.Users.Item.Following.FollowingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The gists property</summary>
        public global::Soenneker.GitHub.OpenApiClient.Users.Item.Gists.GistsRequestBuilder Gists
        {
            get => new global::Soenneker.GitHub.OpenApiClient.Users.Item.Gists.GistsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The gpg_keys property</summary>
        public global::Soenneker.GitHub.OpenApiClient.Users.Item.Gpg_keys.Gpg_keysRequestBuilder Gpg_keys
        {
            get => new global::Soenneker.GitHub.OpenApiClient.Users.Item.Gpg_keys.Gpg_keysRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The hovercard property</summary>
        public global::Soenneker.GitHub.OpenApiClient.Users.Item.Hovercard.HovercardRequestBuilder Hovercard
        {
            get => new global::Soenneker.GitHub.OpenApiClient.Users.Item.Hovercard.HovercardRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The installation property</summary>
        public global::Soenneker.GitHub.OpenApiClient.Users.Item.Installation.InstallationRequestBuilder Installation
        {
            get => new global::Soenneker.GitHub.OpenApiClient.Users.Item.Installation.InstallationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The keys property</summary>
        public global::Soenneker.GitHub.OpenApiClient.Users.Item.Keys.KeysRequestBuilder Keys
        {
            get => new global::Soenneker.GitHub.OpenApiClient.Users.Item.Keys.KeysRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The orgs property</summary>
        public global::Soenneker.GitHub.OpenApiClient.Users.Item.Orgs.OrgsRequestBuilder Orgs
        {
            get => new global::Soenneker.GitHub.OpenApiClient.Users.Item.Orgs.OrgsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The packages property</summary>
        public global::Soenneker.GitHub.OpenApiClient.Users.Item.Packages.PackagesRequestBuilder Packages
        {
            get => new global::Soenneker.GitHub.OpenApiClient.Users.Item.Packages.PackagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The projectsV2 property</summary>
        public global::Soenneker.GitHub.OpenApiClient.Users.Item.ProjectsV2.ProjectsV2RequestBuilder ProjectsV2
        {
            get => new global::Soenneker.GitHub.OpenApiClient.Users.Item.ProjectsV2.ProjectsV2RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The received_events property</summary>
        public global::Soenneker.GitHub.OpenApiClient.Users.Item.Received_events.Received_eventsRequestBuilder Received_events
        {
            get => new global::Soenneker.GitHub.OpenApiClient.Users.Item.Received_events.Received_eventsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The repos property</summary>
        public global::Soenneker.GitHub.OpenApiClient.Users.Item.Repos.ReposRequestBuilder Repos
        {
            get => new global::Soenneker.GitHub.OpenApiClient.Users.Item.Repos.ReposRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The settings property</summary>
        public global::Soenneker.GitHub.OpenApiClient.Users.Item.Settings.SettingsRequestBuilder Settings
        {
            get => new global::Soenneker.GitHub.OpenApiClient.Users.Item.Settings.SettingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The social_accounts property</summary>
        public global::Soenneker.GitHub.OpenApiClient.Users.Item.Social_accounts.Social_accountsRequestBuilder Social_accounts
        {
            get => new global::Soenneker.GitHub.OpenApiClient.Users.Item.Social_accounts.Social_accountsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ssh_signing_keys property</summary>
        public global::Soenneker.GitHub.OpenApiClient.Users.Item.Ssh_signing_keys.Ssh_signing_keysRequestBuilder Ssh_signing_keys
        {
            get => new global::Soenneker.GitHub.OpenApiClient.Users.Item.Ssh_signing_keys.Ssh_signing_keysRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The starred property</summary>
        public global::Soenneker.GitHub.OpenApiClient.Users.Item.Starred.StarredRequestBuilder Starred
        {
            get => new global::Soenneker.GitHub.OpenApiClient.Users.Item.Starred.StarredRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The subscriptions property</summary>
        public global::Soenneker.GitHub.OpenApiClient.Users.Item.Subscriptions.SubscriptionsRequestBuilder Subscriptions
        {
            get => new global::Soenneker.GitHub.OpenApiClient.Users.Item.Subscriptions.SubscriptionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitHub.OpenApiClient.Users.Item.UserItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UserItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/users/{user%2Did}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitHub.OpenApiClient.Users.Item.UserItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UserItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/users/{user%2Did}", rawUrl)
        {
        }
        /// <summary>
        /// Provides publicly available information about someone with a GitHub account.If you are requesting information about an [Enterprise Managed User](https://docs.github.com/enterprise-cloud@latest/admin/managing-iam/understanding-iam-for-enterprises/about-enterprise-managed-users), or a GitHub App bot that is installed in an organization that uses Enterprise Managed Users, your requests must be authenticated as a user or GitHub App that has access to the organization to view that account&apos;s information. If you are not authorized, the request will return a `404 Not Found` status.The `email` key in the following response is the publicly visible email address from your GitHub [profile page](https://github.com/settings/profile). When setting up your profile, you can select a primary email address to be public which provides an email entry for this endpoint. If you do not set a public email address for `email`, then it will have a value of `null`. You only see publicly visible email addresses when authenticated with GitHub. For more information, see [Authentication](https://docs.github.com/rest/guides/getting-started-with-the-rest-api#authentication).The Emails API enables you to list all of your email addresses, and toggle a primary email to be visible publicly. For more information, see [Emails API](https://docs.github.com/rest/users/emails).
        /// API method documentation <see href="https://docs.github.com/rest/users/users#get-a-user" />
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitHub.OpenApiClient.Models.UsersGetByUsername200Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.GitHub.OpenApiClient.Models.BasicError">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.GitHub.OpenApiClient.Models.UsersGetByUsername200Response?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.GitHub.OpenApiClient.Models.UsersGetByUsername200Response> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "404", global::Soenneker.GitHub.OpenApiClient.Models.BasicError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.GitHub.OpenApiClient.Models.UsersGetByUsername200Response>(requestInfo, global::Soenneker.GitHub.OpenApiClient.Models.UsersGetByUsername200Response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Provides publicly available information about someone with a GitHub account.If you are requesting information about an [Enterprise Managed User](https://docs.github.com/enterprise-cloud@latest/admin/managing-iam/understanding-iam-for-enterprises/about-enterprise-managed-users), or a GitHub App bot that is installed in an organization that uses Enterprise Managed Users, your requests must be authenticated as a user or GitHub App that has access to the organization to view that account&apos;s information. If you are not authorized, the request will return a `404 Not Found` status.The `email` key in the following response is the publicly visible email address from your GitHub [profile page](https://github.com/settings/profile). When setting up your profile, you can select a primary email address to be public which provides an email entry for this endpoint. If you do not set a public email address for `email`, then it will have a value of `null`. You only see publicly visible email addresses when authenticated with GitHub. For more information, see [Authentication](https://docs.github.com/rest/guides/getting-started-with-the-rest-api#authentication).The Emails API enables you to list all of your email addresses, and toggle a primary email to be visible publicly. For more information, see [Emails API](https://docs.github.com/rest/users/emails).
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitHub.OpenApiClient.Users.Item.UserItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.GitHub.OpenApiClient.Users.Item.UserItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.GitHub.OpenApiClient.Users.Item.UserItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
