// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.GitHub.OpenApiClient.Orgs.Item.Artifacts.Metadata.DeploymentRecord
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DeploymentRecordPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The deployment cluster.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Cluster { get; set; }
#nullable restore
#else
        public string Cluster { get; set; }
#endif
        /// <summary>The name of the deployment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeploymentName { get; set; }
#nullable restore
#else
        public string DeploymentName { get; set; }
#endif
        /// <summary>The hex encoded digest of the artifact.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Digest { get; set; }
#nullable restore
#else
        public string Digest { get; set; }
#endif
        /// <summary>The name of the GitHub repository associated with the artifact. This should be usedwhen there are no provenance attestations available for the artifact. The repositorymust belong to the organization specified in the path parameter.If a provenance attestation is available for the artifact, the API will usethe repository information from the attestation instead of this parameter.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GithubRepository { get; set; }
#nullable restore
#else
        public string GithubRepository { get; set; }
#endif
        /// <summary>The stage of the deployment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LogicalEnvironment { get; set; }
#nullable restore
#else
        public string LogicalEnvironment { get; set; }
#endif
        /// <summary>The name of the artifact.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The physical region of the deployment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PhysicalEnvironment { get; set; }
#nullable restore
#else
        public string PhysicalEnvironment { get; set; }
#endif
        /// <summary>A list of runtime risks associated with the deployment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.GitHub.OpenApiClient.Orgs.Item.Artifacts.Metadata.DeploymentRecord.DeploymentRecordPostRequestBody_runtime_risks?>? RuntimeRisks { get; set; }
#nullable restore
#else
        public List<global::Soenneker.GitHub.OpenApiClient.Orgs.Item.Artifacts.Metadata.DeploymentRecord.DeploymentRecordPostRequestBody_runtime_risks?> RuntimeRisks { get; set; }
#endif
        /// <summary>The status of the artifact. Can be either deployed or decommissioned.</summary>
        public global::Soenneker.GitHub.OpenApiClient.Orgs.Item.Artifacts.Metadata.DeploymentRecord.DeploymentRecordPostRequestBody_status? Status { get; set; }
        /// <summary>The tags associated with the deployment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Orgs.Item.Artifacts.Metadata.DeploymentRecord.DeploymentRecordPostRequestBody_tags? Tags { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Orgs.Item.Artifacts.Metadata.DeploymentRecord.DeploymentRecordPostRequestBody_tags Tags { get; set; }
#endif
        /// <summary>The artifact version.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Version { get; set; }
#nullable restore
#else
        public string Version { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitHub.OpenApiClient.Orgs.Item.Artifacts.Metadata.DeploymentRecord.DeploymentRecordPostRequestBody"/> and sets the default values.
        /// </summary>
        public DeploymentRecordPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitHub.OpenApiClient.Orgs.Item.Artifacts.Metadata.DeploymentRecord.DeploymentRecordPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.GitHub.OpenApiClient.Orgs.Item.Artifacts.Metadata.DeploymentRecord.DeploymentRecordPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.GitHub.OpenApiClient.Orgs.Item.Artifacts.Metadata.DeploymentRecord.DeploymentRecordPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cluster", n => { Cluster = n.GetStringValue(); } },
                { "deployment_name", n => { DeploymentName = n.GetStringValue(); } },
                { "digest", n => { Digest = n.GetStringValue(); } },
                { "github_repository", n => { GithubRepository = n.GetStringValue(); } },
                { "logical_environment", n => { LogicalEnvironment = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "physical_environment", n => { PhysicalEnvironment = n.GetStringValue(); } },
                { "runtime_risks", n => { RuntimeRisks = n.GetCollectionOfEnumValues<global::Soenneker.GitHub.OpenApiClient.Orgs.Item.Artifacts.Metadata.DeploymentRecord.DeploymentRecordPostRequestBody_runtime_risks>()?.AsList(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.GitHub.OpenApiClient.Orgs.Item.Artifacts.Metadata.DeploymentRecord.DeploymentRecordPostRequestBody_status>(); } },
                { "tags", n => { Tags = n.GetObjectValue<global::Soenneker.GitHub.OpenApiClient.Orgs.Item.Artifacts.Metadata.DeploymentRecord.DeploymentRecordPostRequestBody_tags>(global::Soenneker.GitHub.OpenApiClient.Orgs.Item.Artifacts.Metadata.DeploymentRecord.DeploymentRecordPostRequestBody_tags.CreateFromDiscriminatorValue); } },
                { "version", n => { Version = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("cluster", Cluster);
            writer.WriteStringValue("deployment_name", DeploymentName);
            writer.WriteStringValue("digest", Digest);
            writer.WriteStringValue("github_repository", GithubRepository);
            writer.WriteStringValue("logical_environment", LogicalEnvironment);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("physical_environment", PhysicalEnvironment);
            writer.WriteCollectionOfEnumValues<global::Soenneker.GitHub.OpenApiClient.Orgs.Item.Artifacts.Metadata.DeploymentRecord.DeploymentRecordPostRequestBody_runtime_risks>("runtime_risks", RuntimeRisks);
            writer.WriteEnumValue<global::Soenneker.GitHub.OpenApiClient.Orgs.Item.Artifacts.Metadata.DeploymentRecord.DeploymentRecordPostRequestBody_status>("status", Status);
            writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Orgs.Item.Artifacts.Metadata.DeploymentRecord.DeploymentRecordPostRequestBody_tags>("tags", Tags);
            writer.WriteStringValue("version", Version);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
