// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.GitHub.OpenApiClient.Organizations.Item.Actions.Permissions.ArtifactAndLogRetention;
using Soenneker.GitHub.OpenApiClient.Organizations.Item.Actions.Permissions.ForkPrContributorApproval;
using Soenneker.GitHub.OpenApiClient.Organizations.Item.Actions.Permissions.ForkPrWorkflowsPrivateRepos;
using Soenneker.GitHub.OpenApiClient.Organizations.Item.Actions.Permissions.SelfHostedRunners;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.GitHub.OpenApiClient.Organizations.Item.Actions.Permissions
{
    /// <summary>
    /// Builds and executes requests for operations under \organizations\{org}\actions\permissions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PermissionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The artifactAndLogRetention property</summary>
        public global::Soenneker.GitHub.OpenApiClient.Organizations.Item.Actions.Permissions.ArtifactAndLogRetention.ArtifactAndLogRetentionRequestBuilder ArtifactAndLogRetention
        {
            get => new global::Soenneker.GitHub.OpenApiClient.Organizations.Item.Actions.Permissions.ArtifactAndLogRetention.ArtifactAndLogRetentionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The forkPrContributorApproval property</summary>
        public global::Soenneker.GitHub.OpenApiClient.Organizations.Item.Actions.Permissions.ForkPrContributorApproval.ForkPrContributorApprovalRequestBuilder ForkPrContributorApproval
        {
            get => new global::Soenneker.GitHub.OpenApiClient.Organizations.Item.Actions.Permissions.ForkPrContributorApproval.ForkPrContributorApprovalRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The forkPrWorkflowsPrivateRepos property</summary>
        public global::Soenneker.GitHub.OpenApiClient.Organizations.Item.Actions.Permissions.ForkPrWorkflowsPrivateRepos.ForkPrWorkflowsPrivateReposRequestBuilder ForkPrWorkflowsPrivateRepos
        {
            get => new global::Soenneker.GitHub.OpenApiClient.Organizations.Item.Actions.Permissions.ForkPrWorkflowsPrivateRepos.ForkPrWorkflowsPrivateReposRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The selfHostedRunners property</summary>
        public global::Soenneker.GitHub.OpenApiClient.Organizations.Item.Actions.Permissions.SelfHostedRunners.SelfHostedRunnersRequestBuilder SelfHostedRunners
        {
            get => new global::Soenneker.GitHub.OpenApiClient.Organizations.Item.Actions.Permissions.SelfHostedRunners.SelfHostedRunnersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitHub.OpenApiClient.Organizations.Item.Actions.Permissions.PermissionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PermissionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/organizations/{org}/actions/permissions", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitHub.OpenApiClient.Organizations.Item.Actions.Permissions.PermissionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PermissionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/organizations/{org}/actions/permissions", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
