// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.GitHub.OpenApiClient.Marketplace_listing.Stubbed.Plans.Item.Accounts;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.GitHub.OpenApiClient.Marketplace_listing.Stubbed.Plans.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \marketplace_listing\stubbed\plans\{planId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithPlanItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The accounts property</summary>
        public global::Soenneker.GitHub.OpenApiClient.Marketplace_listing.Stubbed.Plans.Item.Accounts.AccountsRequestBuilder Accounts
        {
            get => new global::Soenneker.GitHub.OpenApiClient.Marketplace_listing.Stubbed.Plans.Item.Accounts.AccountsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitHub.OpenApiClient.Marketplace_listing.Stubbed.Plans.Item.WithPlanItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithPlanItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/marketplace_listing/stubbed/plans/{planId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitHub.OpenApiClient.Marketplace_listing.Stubbed.Plans.Item.WithPlanItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithPlanItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/marketplace_listing/stubbed/plans/{planId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
