// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.GitHub.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RateLimitOverview_resources : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The actions_runner_registration property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.RateLimit? ActionsRunnerRegistration { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.RateLimit ActionsRunnerRegistration { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The code_scanning_autofix property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.RateLimit? CodeScanningAutofix { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.RateLimit CodeScanningAutofix { get; set; }
#endif
        /// <summary>The code_scanning_upload property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.RateLimit? CodeScanningUpload { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.RateLimit CodeScanningUpload { get; set; }
#endif
        /// <summary>The code_search property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.RateLimit? CodeSearch { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.RateLimit CodeSearch { get; set; }
#endif
        /// <summary>The core property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.RateLimit? Core { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.RateLimit Core { get; set; }
#endif
        /// <summary>The dependency_snapshots property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.RateLimit? DependencySnapshots { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.RateLimit DependencySnapshots { get; set; }
#endif
        /// <summary>The graphql property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.RateLimit? Graphql { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.RateLimit Graphql { get; set; }
#endif
        /// <summary>The integration_manifest property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.RateLimit? IntegrationManifest { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.RateLimit IntegrationManifest { get; set; }
#endif
        /// <summary>The scim property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.RateLimit? Scim { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.RateLimit Scim { get; set; }
#endif
        /// <summary>The search property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.RateLimit? Search { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.RateLimit Search { get; set; }
#endif
        /// <summary>The source_import property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.RateLimit? SourceImport { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.RateLimit SourceImport { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitHub.OpenApiClient.Models.RateLimitOverview_resources"/> and sets the default values.
        /// </summary>
        public RateLimitOverview_resources()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitHub.OpenApiClient.Models.RateLimitOverview_resources"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.GitHub.OpenApiClient.Models.RateLimitOverview_resources CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.GitHub.OpenApiClient.Models.RateLimitOverview_resources();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "actions_runner_registration", n => { ActionsRunnerRegistration = n.GetObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.RateLimit>(global::Soenneker.GitHub.OpenApiClient.Models.RateLimit.CreateFromDiscriminatorValue); } },
                { "code_scanning_autofix", n => { CodeScanningAutofix = n.GetObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.RateLimit>(global::Soenneker.GitHub.OpenApiClient.Models.RateLimit.CreateFromDiscriminatorValue); } },
                { "code_scanning_upload", n => { CodeScanningUpload = n.GetObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.RateLimit>(global::Soenneker.GitHub.OpenApiClient.Models.RateLimit.CreateFromDiscriminatorValue); } },
                { "code_search", n => { CodeSearch = n.GetObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.RateLimit>(global::Soenneker.GitHub.OpenApiClient.Models.RateLimit.CreateFromDiscriminatorValue); } },
                { "core", n => { Core = n.GetObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.RateLimit>(global::Soenneker.GitHub.OpenApiClient.Models.RateLimit.CreateFromDiscriminatorValue); } },
                { "dependency_snapshots", n => { DependencySnapshots = n.GetObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.RateLimit>(global::Soenneker.GitHub.OpenApiClient.Models.RateLimit.CreateFromDiscriminatorValue); } },
                { "graphql", n => { Graphql = n.GetObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.RateLimit>(global::Soenneker.GitHub.OpenApiClient.Models.RateLimit.CreateFromDiscriminatorValue); } },
                { "integration_manifest", n => { IntegrationManifest = n.GetObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.RateLimit>(global::Soenneker.GitHub.OpenApiClient.Models.RateLimit.CreateFromDiscriminatorValue); } },
                { "scim", n => { Scim = n.GetObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.RateLimit>(global::Soenneker.GitHub.OpenApiClient.Models.RateLimit.CreateFromDiscriminatorValue); } },
                { "search", n => { Search = n.GetObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.RateLimit>(global::Soenneker.GitHub.OpenApiClient.Models.RateLimit.CreateFromDiscriminatorValue); } },
                { "source_import", n => { SourceImport = n.GetObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.RateLimit>(global::Soenneker.GitHub.OpenApiClient.Models.RateLimit.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.RateLimit>("actions_runner_registration", ActionsRunnerRegistration);
            writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.RateLimit>("code_scanning_autofix", CodeScanningAutofix);
            writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.RateLimit>("code_scanning_upload", CodeScanningUpload);
            writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.RateLimit>("code_search", CodeSearch);
            writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.RateLimit>("core", Core);
            writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.RateLimit>("dependency_snapshots", DependencySnapshots);
            writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.RateLimit>("graphql", Graphql);
            writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.RateLimit>("integration_manifest", IntegrationManifest);
            writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.RateLimit>("scim", Scim);
            writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.RateLimit>("search", Search);
            writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.RateLimit>("source_import", SourceImport);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
