// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitHub.OpenApiClient.Models
{
    /// <summary>Whether it&apos;s a Group Assignment or Individual Assignment.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SimpleClassroomAssignment_type
    {
        [EnumMember(Value = "individual")]
        #pragma warning disable CS1591
        Individual,
        #pragma warning restore CS1591
        [EnumMember(Value = "group")]
        #pragma warning disable CS1591
        Group,
        #pragma warning restore CS1591
    }
}
