// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.GitHub.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.GitHub.OpenApiClient.Models.AddedToProjectIssueEvent"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.ConvertedNoteToIssueIssueEvent"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.DemilestonedIssueEvent"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.LabeledIssueEvent"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.LockedIssueEvent"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.MilestonedIssueEvent"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.MovedColumnInProjectIssueEvent"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.RemovedFromProjectIssueEvent"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.RenamedIssueEvent"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.ReviewDismissedIssueEvent"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.ReviewRequestedIssueEvent"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.ReviewRequestRemovedIssueEvent"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.StateChangeIssueEvent"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.TimelineAssignedIssueEvent"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.TimelineCommentEvent"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.TimelineCommitCommentedEvent"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.TimelineCommittedEvent"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.TimelineCrossReferencedEvent"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.TimelineLineCommentedEvent"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.TimelineReviewedEvent"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.TimelineUnassignedIssueEvent"/>, <see cref="global::Soenneker.GitHub.OpenApiClient.Models.UnlabeledIssueEvent"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TimelineIssueEvents : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.AddedToProjectIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.AddedToProjectIssueEvent? AddedToProjectIssueEvent { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.AddedToProjectIssueEvent AddedToProjectIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.ConvertedNoteToIssueIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.ConvertedNoteToIssueIssueEvent? ConvertedNoteToIssueIssueEvent { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.ConvertedNoteToIssueIssueEvent ConvertedNoteToIssueIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.DemilestonedIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.DemilestonedIssueEvent? DemilestonedIssueEvent { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.DemilestonedIssueEvent DemilestonedIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.LabeledIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.LabeledIssueEvent? LabeledIssueEvent { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.LabeledIssueEvent LabeledIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.LockedIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.LockedIssueEvent? LockedIssueEvent { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.LockedIssueEvent LockedIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.MilestonedIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.MilestonedIssueEvent? MilestonedIssueEvent { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.MilestonedIssueEvent MilestonedIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.MovedColumnInProjectIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.MovedColumnInProjectIssueEvent? MovedColumnInProjectIssueEvent { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.MovedColumnInProjectIssueEvent MovedColumnInProjectIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.RemovedFromProjectIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.RemovedFromProjectIssueEvent? RemovedFromProjectIssueEvent { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.RemovedFromProjectIssueEvent RemovedFromProjectIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.RenamedIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.RenamedIssueEvent? RenamedIssueEvent { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.RenamedIssueEvent RenamedIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.ReviewDismissedIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.ReviewDismissedIssueEvent? ReviewDismissedIssueEvent { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.ReviewDismissedIssueEvent ReviewDismissedIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.ReviewRequestedIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.ReviewRequestedIssueEvent? ReviewRequestedIssueEvent { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.ReviewRequestedIssueEvent ReviewRequestedIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.ReviewRequestRemovedIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.ReviewRequestRemovedIssueEvent? ReviewRequestRemovedIssueEvent { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.ReviewRequestRemovedIssueEvent ReviewRequestRemovedIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.StateChangeIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.StateChangeIssueEvent? StateChangeIssueEvent { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.StateChangeIssueEvent StateChangeIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.TimelineAssignedIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.TimelineAssignedIssueEvent? TimelineAssignedIssueEvent { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.TimelineAssignedIssueEvent TimelineAssignedIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.TimelineCommentEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.TimelineCommentEvent? TimelineCommentEvent { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.TimelineCommentEvent TimelineCommentEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.TimelineCommitCommentedEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.TimelineCommitCommentedEvent? TimelineCommitCommentedEvent { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.TimelineCommitCommentedEvent TimelineCommitCommentedEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.TimelineCommittedEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.TimelineCommittedEvent? TimelineCommittedEvent { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.TimelineCommittedEvent TimelineCommittedEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.TimelineCrossReferencedEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.TimelineCrossReferencedEvent? TimelineCrossReferencedEvent { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.TimelineCrossReferencedEvent TimelineCrossReferencedEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.TimelineLineCommentedEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.TimelineLineCommentedEvent? TimelineLineCommentedEvent { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.TimelineLineCommentedEvent TimelineLineCommentedEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.TimelineReviewedEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.TimelineReviewedEvent? TimelineReviewedEvent { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.TimelineReviewedEvent TimelineReviewedEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.TimelineUnassignedIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.TimelineUnassignedIssueEvent? TimelineUnassignedIssueEvent { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.TimelineUnassignedIssueEvent TimelineUnassignedIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitHub.OpenApiClient.Models.UnlabeledIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitHub.OpenApiClient.Models.UnlabeledIssueEvent? UnlabeledIssueEvent { get; set; }
#nullable restore
#else
        public global::Soenneker.GitHub.OpenApiClient.Models.UnlabeledIssueEvent UnlabeledIssueEvent { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitHub.OpenApiClient.Models.TimelineIssueEvents"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.GitHub.OpenApiClient.Models.TimelineIssueEvents CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.GitHub.OpenApiClient.Models.TimelineIssueEvents();
            result.AddedToProjectIssueEvent = new global::Soenneker.GitHub.OpenApiClient.Models.AddedToProjectIssueEvent();
            result.ConvertedNoteToIssueIssueEvent = new global::Soenneker.GitHub.OpenApiClient.Models.ConvertedNoteToIssueIssueEvent();
            result.DemilestonedIssueEvent = new global::Soenneker.GitHub.OpenApiClient.Models.DemilestonedIssueEvent();
            result.LabeledIssueEvent = new global::Soenneker.GitHub.OpenApiClient.Models.LabeledIssueEvent();
            result.LockedIssueEvent = new global::Soenneker.GitHub.OpenApiClient.Models.LockedIssueEvent();
            result.MilestonedIssueEvent = new global::Soenneker.GitHub.OpenApiClient.Models.MilestonedIssueEvent();
            result.MovedColumnInProjectIssueEvent = new global::Soenneker.GitHub.OpenApiClient.Models.MovedColumnInProjectIssueEvent();
            result.RemovedFromProjectIssueEvent = new global::Soenneker.GitHub.OpenApiClient.Models.RemovedFromProjectIssueEvent();
            result.RenamedIssueEvent = new global::Soenneker.GitHub.OpenApiClient.Models.RenamedIssueEvent();
            result.ReviewDismissedIssueEvent = new global::Soenneker.GitHub.OpenApiClient.Models.ReviewDismissedIssueEvent();
            result.ReviewRequestedIssueEvent = new global::Soenneker.GitHub.OpenApiClient.Models.ReviewRequestedIssueEvent();
            result.ReviewRequestRemovedIssueEvent = new global::Soenneker.GitHub.OpenApiClient.Models.ReviewRequestRemovedIssueEvent();
            result.StateChangeIssueEvent = new global::Soenneker.GitHub.OpenApiClient.Models.StateChangeIssueEvent();
            result.TimelineAssignedIssueEvent = new global::Soenneker.GitHub.OpenApiClient.Models.TimelineAssignedIssueEvent();
            result.TimelineCommentEvent = new global::Soenneker.GitHub.OpenApiClient.Models.TimelineCommentEvent();
            result.TimelineCommitCommentedEvent = new global::Soenneker.GitHub.OpenApiClient.Models.TimelineCommitCommentedEvent();
            result.TimelineCommittedEvent = new global::Soenneker.GitHub.OpenApiClient.Models.TimelineCommittedEvent();
            result.TimelineCrossReferencedEvent = new global::Soenneker.GitHub.OpenApiClient.Models.TimelineCrossReferencedEvent();
            result.TimelineLineCommentedEvent = new global::Soenneker.GitHub.OpenApiClient.Models.TimelineLineCommentedEvent();
            result.TimelineReviewedEvent = new global::Soenneker.GitHub.OpenApiClient.Models.TimelineReviewedEvent();
            result.TimelineUnassignedIssueEvent = new global::Soenneker.GitHub.OpenApiClient.Models.TimelineUnassignedIssueEvent();
            result.UnlabeledIssueEvent = new global::Soenneker.GitHub.OpenApiClient.Models.UnlabeledIssueEvent();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(AddedToProjectIssueEvent != null || ConvertedNoteToIssueIssueEvent != null || DemilestonedIssueEvent != null || LabeledIssueEvent != null || LockedIssueEvent != null || MilestonedIssueEvent != null || MovedColumnInProjectIssueEvent != null || RemovedFromProjectIssueEvent != null || RenamedIssueEvent != null || ReviewDismissedIssueEvent != null || ReviewRequestedIssueEvent != null || ReviewRequestRemovedIssueEvent != null || StateChangeIssueEvent != null || TimelineAssignedIssueEvent != null || TimelineCommentEvent != null || TimelineCommitCommentedEvent != null || TimelineCommittedEvent != null || TimelineCrossReferencedEvent != null || TimelineLineCommentedEvent != null || TimelineReviewedEvent != null || TimelineUnassignedIssueEvent != null || UnlabeledIssueEvent != null)
            {
                return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(AddedToProjectIssueEvent, ConvertedNoteToIssueIssueEvent, DemilestonedIssueEvent, LabeledIssueEvent, LockedIssueEvent, MilestonedIssueEvent, MovedColumnInProjectIssueEvent, RemovedFromProjectIssueEvent, RenamedIssueEvent, ReviewDismissedIssueEvent, ReviewRequestedIssueEvent, ReviewRequestRemovedIssueEvent, StateChangeIssueEvent, TimelineAssignedIssueEvent, TimelineCommentEvent, TimelineCommitCommentedEvent, TimelineCommittedEvent, TimelineCrossReferencedEvent, TimelineLineCommentedEvent, TimelineReviewedEvent, TimelineUnassignedIssueEvent, UnlabeledIssueEvent);
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.GitHub.OpenApiClient.Models.AddedToProjectIssueEvent>(null, AddedToProjectIssueEvent, ConvertedNoteToIssueIssueEvent, DemilestonedIssueEvent, LabeledIssueEvent, LockedIssueEvent, MilestonedIssueEvent, MovedColumnInProjectIssueEvent, RemovedFromProjectIssueEvent, RenamedIssueEvent, ReviewDismissedIssueEvent, ReviewRequestedIssueEvent, ReviewRequestRemovedIssueEvent, StateChangeIssueEvent, TimelineAssignedIssueEvent, TimelineCommentEvent, TimelineCommitCommentedEvent, TimelineCommittedEvent, TimelineCrossReferencedEvent, TimelineLineCommentedEvent, TimelineReviewedEvent, TimelineUnassignedIssueEvent, UnlabeledIssueEvent);
        }
    }
}
#pragma warning restore CS0618
